{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "e7b02b55",
   "metadata": {
    "_cell_guid": "09bf3064-67db-43dd-addf-238d6c16f6a2",
    "_uuid": "3ae59b2e-c53c-45a2-8526-ae3355473bc3",
    "collapsed": false,
    "execution": {
     "iopub.execute_input": "2026-04-09T03:22:27.476875Z",
     "iopub.status.busy": "2026-04-09T03:22:27.475390Z",
     "iopub.status.idle": "2026-04-09T03:35:47.461008Z",
     "shell.execute_reply": "2026-04-09T03:35:47.459941Z"
    },
    "jupyter": {
     "outputs_hidden": false
    },
    "papermill": {
     "duration": 799.992763,
     "end_time": "2026-04-09T03:35:47.463609+00:00",
     "exception": false,
     "start_time": "2026-04-09T03:22:27.470846+00:00",
     "status": "completed"
    },
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      ">>> Initialized: Structural Adjacency Matrix (Prior Graph).\n",
      ">>> Tìm thấy 88 subjects. Bắt đầu trích xuất Hybrid Features...\n",
      "Finished sub-001: Epochs=291 | Tensor Shape=(291, 19, 8)\n",
      "Finished sub-002: Epochs=291 | Tensor Shape=(291, 19, 8)\n",
      "Finished sub-003: Epochs=291 | Tensor Shape=(291, 19, 8)\n",
      "Finished sub-004: Epochs=291 | Tensor Shape=(291, 19, 8)\n",
      "Finished sub-005: Epochs=291 | Tensor Shape=(291, 19, 8)\n",
      "Finished sub-006: Epochs=291 | Tensor Shape=(291, 19, 8)\n",
      "Finished sub-007: Epochs=291 | Tensor Shape=(291, 19, 8)\n",
      "Finished sub-008: Epochs=291 | Tensor Shape=(291, 19, 8)\n",
      "Finished sub-009: Epochs=291 | Tensor Shape=(291, 19, 8)\n",
      "Finished sub-010: Epochs=291 | Tensor Shape=(291, 19, 8)\n",
      "Finished sub-011: Epochs=291 | Tensor Shape=(291, 19, 8)\n",
      "Finished sub-012: Epochs=291 | Tensor Shape=(291, 19, 8)\n",
      "Finished sub-013: Epochs=291 | Tensor Shape=(291, 19, 8)\n",
      "Finished sub-014: Epochs=291 | Tensor Shape=(291, 19, 8)\n",
      "Finished sub-015: Epochs=291 | Tensor Shape=(291, 19, 8)\n",
      "Finished sub-016: Epochs=291 | Tensor Shape=(291, 19, 8)\n",
      "Finished sub-017: Epochs=291 | Tensor Shape=(291, 19, 8)\n",
      "Finished sub-018: Epochs=291 | Tensor Shape=(291, 19, 8)\n",
      "Finished sub-019: Epochs=291 | Tensor Shape=(291, 19, 8)\n",
      "Finished sub-020: Epochs=291 | Tensor Shape=(291, 19, 8)\n",
      "Finished sub-021: Epochs=291 | Tensor Shape=(291, 19, 8)\n",
      "Finished sub-022: Epochs=291 | Tensor Shape=(291, 19, 8)\n",
      "Finished sub-023: Epochs=291 | Tensor Shape=(291, 19, 8)\n",
      "Finished sub-024: Epochs=291 | Tensor Shape=(291, 19, 8)\n",
      "Finished sub-025: Epochs=291 | Tensor Shape=(291, 19, 8)\n",
      "Finished sub-026: Epochs=291 | Tensor Shape=(291, 19, 8)\n",
      "Finished sub-027: Epochs=291 | Tensor Shape=(291, 19, 8)\n",
      "Finished sub-028: Epochs=291 | Tensor Shape=(291, 19, 8)\n",
      "Finished sub-029: Epochs=291 | Tensor Shape=(291, 19, 8)\n",
      "Finished sub-030: Epochs=291 | Tensor Shape=(291, 19, 8)\n",
      "Finished sub-031: Epochs=291 | Tensor Shape=(291, 19, 8)\n",
      "Finished sub-032: Epochs=291 | Tensor Shape=(291, 19, 8)\n",
      "Finished sub-033: Epochs=291 | Tensor Shape=(291, 19, 8)\n",
      "Finished sub-034: Epochs=291 | Tensor Shape=(291, 19, 8)\n",
      "Finished sub-035: Epochs=291 | Tensor Shape=(291, 19, 8)\n",
      "Finished sub-036: Epochs=291 | Tensor Shape=(291, 19, 8)\n",
      "Finished sub-037: Epochs=291 | Tensor Shape=(291, 19, 8)\n",
      "Finished sub-038: Epochs=291 | Tensor Shape=(291, 19, 8)\n",
      "Finished sub-039: Epochs=291 | Tensor Shape=(291, 19, 8)\n",
      "Finished sub-040: Epochs=291 | Tensor Shape=(291, 19, 8)\n",
      "Finished sub-041: Epochs=291 | Tensor Shape=(291, 19, 8)\n",
      "Finished sub-042: Epochs=291 | Tensor Shape=(291, 19, 8)\n",
      "Finished sub-043: Epochs=291 | Tensor Shape=(291, 19, 8)\n",
      "Finished sub-044: Epochs=291 | Tensor Shape=(291, 19, 8)\n",
      "Finished sub-045: Epochs=291 | Tensor Shape=(291, 19, 8)\n",
      "Finished sub-046: Epochs=291 | Tensor Shape=(291, 19, 8)\n",
      "Finished sub-047: Epochs=291 | Tensor Shape=(291, 19, 8)\n",
      "Finished sub-048: Epochs=291 | Tensor Shape=(291, 19, 8)\n",
      "Finished sub-049: Epochs=291 | Tensor Shape=(291, 19, 8)\n",
      "Finished sub-050: Epochs=291 | Tensor Shape=(291, 19, 8)\n",
      "Finished sub-051: Epochs=291 | Tensor Shape=(291, 19, 8)\n",
      "Finished sub-052: Epochs=291 | Tensor Shape=(291, 19, 8)\n",
      "Finished sub-053: Epochs=291 | Tensor Shape=(291, 19, 8)\n",
      "Finished sub-054: Epochs=291 | Tensor Shape=(291, 19, 8)\n",
      "Finished sub-055: Epochs=291 | Tensor Shape=(291, 19, 8)\n",
      "Finished sub-056: Epochs=291 | Tensor Shape=(291, 19, 8)\n",
      "Finished sub-057: Epochs=291 | Tensor Shape=(291, 19, 8)\n",
      "Finished sub-058: Epochs=291 | Tensor Shape=(291, 19, 8)\n",
      "Finished sub-059: Epochs=291 | Tensor Shape=(291, 19, 8)\n",
      "Finished sub-060: Epochs=291 | Tensor Shape=(291, 19, 8)\n",
      "Finished sub-061: Epochs=291 | Tensor Shape=(291, 19, 8)\n",
      "Finished sub-062: Epochs=291 | Tensor Shape=(291, 19, 8)\n",
      "Finished sub-063: Epochs=291 | Tensor Shape=(291, 19, 8)\n",
      "Finished sub-064: Epochs=291 | Tensor Shape=(291, 19, 8)\n",
      "Finished sub-065: Epochs=291 | Tensor Shape=(291, 19, 8)\n",
      "Finished sub-066: Epochs=291 | Tensor Shape=(291, 19, 8)\n",
      "Finished sub-067: Epochs=291 | Tensor Shape=(291, 19, 8)\n",
      "Finished sub-068: Epochs=291 | Tensor Shape=(291, 19, 8)\n",
      "Finished sub-069: Epochs=291 | Tensor Shape=(291, 19, 8)\n",
      "Finished sub-070: Epochs=291 | Tensor Shape=(291, 19, 8)\n",
      "Finished sub-071: Epochs=291 | Tensor Shape=(291, 19, 8)\n",
      "Finished sub-072: Epochs=291 | Tensor Shape=(291, 19, 8)\n",
      "Finished sub-073: Epochs=291 | Tensor Shape=(291, 19, 8)\n",
      "Finished sub-074: Epochs=291 | Tensor Shape=(291, 19, 8)\n",
      "Finished sub-075: Epochs=291 | Tensor Shape=(291, 19, 8)\n",
      "Finished sub-076: Epochs=291 | Tensor Shape=(291, 19, 8)\n",
      "Finished sub-077: Epochs=291 | Tensor Shape=(291, 19, 8)\n",
      "Finished sub-078: Epochs=291 | Tensor Shape=(291, 19, 8)\n",
      "Finished sub-079: Epochs=291 | Tensor Shape=(291, 19, 8)\n",
      "Finished sub-080: Epochs=291 | Tensor Shape=(291, 19, 8)\n",
      "Finished sub-081: Epochs=291 | Tensor Shape=(291, 19, 8)\n",
      "Finished sub-082: Epochs=291 | Tensor Shape=(291, 19, 8)\n",
      "Finished sub-083: Epochs=291 | Tensor Shape=(291, 19, 8)\n",
      "Finished sub-084: Epochs=291 | Tensor Shape=(291, 19, 8)\n",
      "Finished sub-085: Epochs=291 | Tensor Shape=(291, 19, 8)\n",
      "Finished sub-086: Epochs=291 | Tensor Shape=(291, 19, 8)\n",
      "Finished sub-087: Epochs=291 | Tensor Shape=(291, 19, 8)\n",
      "Finished sub-088: Epochs=291 | Tensor Shape=(291, 19, 8)\n",
      "\n",
      ">>> HOÀN TẤT: Đã xử lý 88/88 subjects.\n",
      ">>> Tensor Dữ liệu (Epochs, 19, 8) lưu tại: /kaggle/working/processed_data\n"
     ]
    }
   ],
   "source": [
    "import os\n",
    "import glob\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "import mne\n",
    "import warnings\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "from sklearn.preprocessing import StandardScaler\n",
    "from scipy.signal import welch\n",
    "\n",
    "# Tắt cảnh báo MNE\n",
    "warnings.filterwarnings(\"ignore\")\n",
    "mne.set_log_level('ERROR')\n",
    "\n",
    "# ==============================================================================\n",
    "# 1. CẤU HÌNH THAM SỐ LÂM SÀNG\n",
    "# ==============================================================================\n",
    "\n",
    "BANDS = {\n",
    "    'Delta': (0.5, 4),\n",
    "    'Theta': (4, 8),\n",
    "    'Alpha': (8, 13),\n",
    "    'Beta': (13, 25),\n",
    "    'Gamma': (25, 45)\n",
    "}\n",
    "\n",
    "# Thông số Cửa sổ trượt\n",
    "WINDOW_SIZE = 10  # 10 giây\n",
    "OVERLAP = 0.9     # Chồng lấp 90%\n",
    "DURATION_LIMIT = 300  # Giới hạn 5 phút (300s)\n",
    "\n",
    "STANDARD_CHANNELS = [\n",
    "    'Fp1', 'Fp2', 'F7', 'F3', 'Fz', 'F4', 'F8', \n",
    "    'T3', 'C3', 'Cz', 'C4', 'T4', 'T5', 'P3', \n",
    "    'Pz', 'P4', 'T6', 'O1', 'O2'\n",
    "]\n",
    "\n",
    "BRAIN_REGIONS = {\n",
    "    'Frontal': ['Fp1', 'Fp2', 'F7', 'F3', 'Fz', 'F4', 'F8'],\n",
    "    'Central': ['C3', 'Cz', 'C4'],\n",
    "    'Parietal': ['P3', 'Pz', 'P4'],\n",
    "    'Temporal': ['T3', 'T4', 'T5', 'T6'],\n",
    "    'Occipital': ['O1', 'O2']\n",
    "}\n",
    "\n",
    "# ==============================================================================\n",
    "# 2. HÀM TRÍCH XUẤT ĐẶC TRƯNG LAI ĐA MIỀN (HYBRID FEATURES)\n",
    "# ==============================================================================\n",
    "\n",
    "def calculate_psd_features(signal_segment, sfreq):\n",
    "    \"\"\"\n",
    "    MIỀN TẦN SỐ: Tính Mật độ phổ công suất (PSD) cho 5 dải tần.\n",
    "    Input: Đoạn tín hiệu (19 Kênh, 2500 Điểm)\n",
    "    Output: Ma trận (19 Kênh, 5 Đặc trưng)\n",
    "    \"\"\"\n",
    "    n_channels = signal_segment.shape[0]\n",
    "    psd_features = np.zeros((n_channels, 5))\n",
    "    \n",
    "    # nperseg = sfreq * 2 (Cửa sổ Welch 2 giây -> Độ phân giải tần số 0.5 Hz)\n",
    "    for ch in range(n_channels):\n",
    "        freqs, psd = welch(signal_segment[ch], fs=sfreq, nperseg=int(sfreq * 2))\n",
    "        \n",
    "        # SỬA LỖI NUMPY 2.0 TẠI ĐÂY: Dùng np.trapezoid thay cho np.trapz\n",
    "        total_power = np.trapezoid(psd, freqs)\n",
    "        if total_power == 0: total_power = 1e-9\n",
    "            \n",
    "        for i, (band, (f_min, f_max)) in enumerate(BANDS.items()):\n",
    "            idx = np.logical_and(freqs >= f_min, freqs < f_max)\n",
    "            # SỬA LỖI NUMPY 2.0 TẠI ĐÂY: Dùng np.trapezoid\n",
    "            band_power = np.trapezoid(psd[idx], freqs[idx])\n",
    "            psd_features[ch, i] = band_power / total_power\n",
    "            \n",
    "    return psd_features\n",
    "\n",
    "def calculate_hjorth_parameters(signal_segment):\n",
    "    \"\"\"\n",
    "    MIỀN THỜI GIAN: Tính 3 thông số Hjorth bằng Vector hóa siêu tốc.\n",
    "    Input: Đoạn tín hiệu (19 Kênh, 2500 Điểm)\n",
    "    Output: Ma trận (19 Kênh, 3 Đặc trưng)\n",
    "    \"\"\"\n",
    "    eps = 1e-10\n",
    "    \n",
    "    # Tính đạo hàm bậc 1 và 2 dọc theo trục thời gian\n",
    "    dx = np.diff(signal_segment, axis=1)\n",
    "    ddx = np.diff(dx, axis=1)\n",
    "    \n",
    "    # 1. Activity (Phương sai)\n",
    "    activity = np.var(signal_segment, axis=1)\n",
    "    \n",
    "    # 2. Mobility (Sự linh hoạt)\n",
    "    var_dx = np.var(dx, axis=1)\n",
    "    mobility = np.sqrt(var_dx / (activity + eps))\n",
    "    \n",
    "    # 3. Complexity (Độ phức tạp)\n",
    "    var_ddx = np.var(ddx, axis=1)\n",
    "    mobility_dx = np.sqrt(var_ddx / (var_dx + eps))\n",
    "    complexity = mobility_dx / (mobility + eps)\n",
    "    \n",
    "    return np.column_stack((activity, mobility, complexity))\n",
    "\n",
    "def create_structural_adjacency():\n",
    "    \"\"\" Tạo ma trận kề Vật lý (Prior Spatial Graph) \"\"\"\n",
    "    n_nodes = len(STANDARD_CHANNELS)\n",
    "    adj = np.zeros((n_nodes, n_nodes))\n",
    "    \n",
    "    chan_to_region = {}\n",
    "    for region, chans in BRAIN_REGIONS.items():\n",
    "        for ch in chans: chan_to_region[ch] = region\n",
    "            \n",
    "    for i, ch1 in enumerate(STANDARD_CHANNELS):\n",
    "        for j, ch2 in enumerate(STANDARD_CHANNELS):\n",
    "            region1 = chan_to_region.get(ch1)\n",
    "            region2 = chan_to_region.get(ch2)\n",
    "            if region1 and region2 and region1 == region2:\n",
    "                adj[i, j] = 1\n",
    "    return adj\n",
    "\n",
    "# ==============================================================================\n",
    "# 3. QUY TRÌNH XỬ LÝ (SUBJECT PROCESSING)\n",
    "# ==============================================================================\n",
    "\n",
    "def process_one_subject(file_path, save_dir, sub_id):\n",
    "    try:\n",
    "        # --- BƯỚC 1: ĐỌC VÀ TIỀN XỬ LÝ ---\n",
    "        raw = mne.io.read_raw_eeglab(file_path, preload=True, verbose=False)\n",
    "        available_chans = raw.info['ch_names']\n",
    "        picks = [ch for ch in STANDARD_CHANNELS if ch in available_chans]\n",
    "        \n",
    "        if len(picks) < len(STANDARD_CHANNELS):\n",
    "            print(f\"BỎ QUA {sub_id}: Thiếu kênh (Tìm thấy {len(picks)}/19).\")\n",
    "            return\n",
    "\n",
    "        raw.pick_channels(picks, ordered=True)\n",
    "        raw.set_eeg_reference('average', projection=False)\n",
    "        \n",
    "        if raw.times[-1] > DURATION_LIMIT:\n",
    "            raw.crop(tmin=0, tmax=DURATION_LIMIT)\n",
    "\n",
    "        # Xử lý NaN rác\n",
    "        data = raw.get_data()\n",
    "        if np.isnan(data).any():\n",
    "            raw._data = np.nan_to_num(data, nan=0.0)\n",
    "\n",
    "        # Lọc Broadband (0.5 - 45 Hz) CHỈ 1 LẦN DUY NHẤT\n",
    "        try:\n",
    "            raw.filter(0.5, 45.0, method='iir', verbose=False)\n",
    "        except:\n",
    "            raw.filter(0.5, 45.0, verbose=False)\n",
    "            \n",
    "        filtered_data = raw.get_data()\n",
    "\n",
    "        # --- BƯỚC 2: CẮT CỬA SỔ VÀ TRÍCH XUẤT ĐẶC TRƯNG ---\n",
    "        sfreq = raw.info['sfreq']\n",
    "        window_samples = int(WINDOW_SIZE * sfreq)\n",
    "        step_samples = int(window_samples * (1 - OVERLAP))\n",
    "        total_samples = raw.n_times\n",
    "        \n",
    "        features_list = []\n",
    "        \n",
    "        # Sliding Window Loop\n",
    "        for start in range(0, total_samples - window_samples + 1, step_samples):\n",
    "            end = start + window_samples\n",
    "            data_segment = filtered_data[:, start:end]\n",
    "            \n",
    "            # Clip nhiễu quá lớn (+/- 250uV) để bảo vệ Hjorth\n",
    "            data_segment = np.clip(data_segment, -250e-6, 250e-6)\n",
    "            \n",
    "            # Khai thác song song 2 miền\n",
    "            psd_feats = calculate_psd_features(data_segment, sfreq)\n",
    "            hjorth_feats = calculate_hjorth_parameters(data_segment)\n",
    "            \n",
    "            # Ghép nối: 5 PSD + 3 Hjorth = 8 Đặc trưng\n",
    "            # Kích thước segment_features: (19, 8)\n",
    "            segment_features = np.concatenate((psd_feats, hjorth_feats), axis=1)\n",
    "            features_list.append(segment_features)\n",
    "\n",
    "        if not features_list:\n",
    "            print(f\"Cảnh báo: Không tạo được đoạn nào cho {sub_id}\")\n",
    "            return\n",
    "\n",
    "        # Kích thước all_features: (n_segs, 19, 8)\n",
    "        all_features = np.array(features_list)\n",
    "        n_segs = all_features.shape[0]\n",
    "        \n",
    "        # --- BƯỚC 3: KHÔNG CHUẨN HÓA Ở ĐÂY NỮA ---\n",
    "        # Chỉ đơn giản là định hình lại và xử lý NaN\n",
    "        features_flat = all_features.reshape(-1, 8)\n",
    "        features_flat = np.nan_to_num(features_flat, nan=0.0, posinf=0.0, neginf=0.0)\n",
    "        \n",
    "        # Gấp lại thành (n_segs, 19, 8) ĐỂ LƯU GIỮ NGUYÊN BẢN (RAW)\n",
    "        final_tensor = features_flat.reshape(n_segs, 19, 8)\n",
    "\n",
    "        # --- BƯỚC 4: LƯU TENSOR ĐẦU RA ---\n",
    "        feat_path = os.path.join(save_dir, f\"{sub_id}_features.npy\")\n",
    "        np.save(feat_path, final_tensor.astype(np.float32))\n",
    "        \n",
    "        print(f\"Finished {sub_id}: Epochs={n_segs} | Tensor Shape={final_tensor.shape}\")\n",
    "\n",
    "    except Exception as e:\n",
    "        print(f\"FAILED {sub_id}: {str(e)}\")\n",
    "\n",
    "# ==============================================================================\n",
    "# 4. HÀM MAIN\n",
    "# ==============================================================================\n",
    "\n",
    "def main_processing():\n",
    "    RAW_DATA_ROOT = r\"/kaggle/input/datasets/dtandat/mf-mgcn-datasets/ds004504\" # Thay đổi đường dẫn thực tế của bạn\n",
    "    \n",
    "    BASE_DIR = '/kaggle/working'\n",
    "    PROCESSED_DIR = os.path.join(BASE_DIR, \"processed_data\")\n",
    "    \n",
    "    if not os.path.exists(PROCESSED_DIR):\n",
    "        os.makedirs(PROCESSED_DIR)\n",
    "        \n",
    "    # Tạo ma trận cấu trúc (Chỉ cần 1 lần)\n",
    "    struct_adj = create_structural_adjacency()\n",
    "    pd.DataFrame(struct_adj).to_csv(os.path.join(PROCESSED_DIR, \"structural_adjacency.csv\"), header=False, index=False)\n",
    "    print(\">>> Initialized: Structural Adjacency Matrix (Prior Graph).\")\n",
    "\n",
    "    if not os.path.exists(RAW_DATA_ROOT):\n",
    "        print(f\"ERROR: Không tìm thấy thư mục {RAW_DATA_ROOT}\")\n",
    "        return\n",
    "\n",
    "    sub_folders = [f for f in os.listdir(RAW_DATA_ROOT) if f.startswith('sub-')]\n",
    "    sub_folders.sort()\n",
    "    \n",
    "    print(f\">>> Tìm thấy {len(sub_folders)} subjects. Bắt đầu trích xuất Hybrid Features...\")\n",
    "    \n",
    "    count = 0\n",
    "    for sub_id in sub_folders:\n",
    "        eeg_path = os.path.join(RAW_DATA_ROOT, sub_id, 'eeg')\n",
    "        set_files = glob.glob(os.path.join(eeg_path, \"*.set\"))\n",
    "        \n",
    "        if set_files:\n",
    "            process_one_subject(set_files[0], PROCESSED_DIR, sub_id)\n",
    "            count += 1\n",
    "        else:\n",
    "            print(f\"Warning: Không có file .set cho {sub_id}\")\n",
    "            \n",
    "    print(f\"\\n>>> HOÀN TẤT: Đã xử lý {count}/{len(sub_folders)} subjects.\")\n",
    "    print(f\">>> Tensor Dữ liệu (Epochs, 19, 8) lưu tại: {PROCESSED_DIR}\")\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    main_processing()"
   ]
  }
 ],
 "metadata": {
  "kaggle": {
   "accelerator": "none",
   "dataSources": [
    {
     "databundleVersionId": 16542997,
     "datasetId": 9989031,
     "sourceId": 15609361,
     "sourceType": "datasetVersion"
    }
   ],
   "dockerImageVersionId": 31328,
   "isGpuEnabled": false,
   "isInternetEnabled": true,
   "language": "python",
   "sourceType": "notebook"
  },
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.12"
  },
  "papermill": {
   "default_parameters": {},
   "duration": 804.591195,
   "end_time": "2026-04-09T03:35:48.491907+00:00",
   "environment_variables": {},
   "exception": null,
   "input_path": "__notebook__.ipynb",
   "output_path": "__notebook__.ipynb",
   "parameters": {},
   "start_time": "2026-04-09T03:22:23.900712+00:00",
   "version": "2.7.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
