{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "fcd4368a",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2026-04-09T07:37:58.519019Z",
     "iopub.status.busy": "2026-04-09T07:37:58.518768Z",
     "iopub.status.idle": "2026-04-09T07:38:08.221183Z",
     "shell.execute_reply": "2026-04-09T07:38:08.220440Z"
    },
    "papermill": {
     "duration": 9.706937,
     "end_time": "2026-04-09T07:38:08.222920+00:00",
     "exception": false,
     "start_time": "2026-04-09T07:37:58.515983+00:00",
     "status": "completed"
    },
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting torch_geometric\r\n",
      "  Downloading torch_geometric-2.7.0-py3-none-any.whl.metadata (63 kB)\r\n",
      "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m63.7/63.7 kB\u001b[0m \u001b[31m2.9 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\r\n",
      "\u001b[?25hRequirement already satisfied: aiohttp in /usr/local/lib/python3.12/dist-packages (from torch_geometric) (3.13.3)\r\n",
      "Requirement already satisfied: fsspec in /usr/local/lib/python3.12/dist-packages (from torch_geometric) (2026.2.0)\r\n",
      "Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch_geometric) (3.1.6)\r\n",
      "Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from torch_geometric) (2.0.2)\r\n",
      "Requirement already satisfied: psutil>=5.8.0 in /usr/local/lib/python3.12/dist-packages (from torch_geometric) (5.9.5)\r\n",
      "Requirement already satisfied: pyparsing in /usr/local/lib/python3.12/dist-packages (from torch_geometric) (3.3.2)\r\n",
      "Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from torch_geometric) (2.32.4)\r\n",
      "Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from torch_geometric) (4.67.3)\r\n",
      "Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from torch_geometric) (3.6.0)\r\n",
      "Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->torch_geometric) (2.6.1)\r\n",
      "Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->torch_geometric) (1.4.0)\r\n",
      "Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->torch_geometric) (25.4.0)\r\n",
      "Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp->torch_geometric) (1.8.0)\r\n",
      "Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp->torch_geometric) (6.7.1)\r\n",
      "Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->torch_geometric) (0.4.1)\r\n",
      "Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->torch_geometric) (1.22.0)\r\n",
      "Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch_geometric) (3.0.3)\r\n",
      "Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->torch_geometric) (3.4.4)\r\n",
      "Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->torch_geometric) (3.11)\r\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->torch_geometric) (2.5.0)\r\n",
      "Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->torch_geometric) (2026.1.4)\r\n",
      "Requirement already satisfied: typing-extensions>=4.2 in /usr/local/lib/python3.12/dist-packages (from aiosignal>=1.4.0->aiohttp->torch_geometric) (4.15.0)\r\n",
      "Downloading torch_geometric-2.7.0-py3-none-any.whl (1.3 MB)\r\n",
      "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m1.3/1.3 MB\u001b[0m \u001b[31m25.1 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\r\n",
      "\u001b[?25hInstalling collected packages: torch_geometric\r\n",
      "Successfully installed torch_geometric-2.7.0\r\n",
      "Looking in links: https://data.pyg.org/whl/torch-2.10.0+cu128.html\r\n",
      "Collecting torch-scatter\r\n",
      "  Downloading https://data.pyg.org/whl/torch-2.10.0%2Bcu128/torch_scatter-2.1.2%2Bpt210cu128-cp312-cp312-linux_x86_64.whl (10.9 MB)\r\n",
      "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m10.9/10.9 MB\u001b[0m \u001b[31m54.6 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\r\n",
      "\u001b[?25hInstalling collected packages: torch-scatter\r\n",
      "Successfully installed torch-scatter-2.1.2+pt210cu128\r\n"
     ]
    }
   ],
   "source": [
    "!pip install torch_geometric\n",
    "!pip install torch-scatter -f https://data.pyg.org/whl/torch-2.10.0+cu128.html"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "fa387560",
   "metadata": {
    "_cell_guid": "0ad39be2-d511-405b-876c-b8c85a5e2c27",
    "_uuid": "883f90f2-976d-453f-ab4a-90d1bfeb05b5",
    "collapsed": false,
    "execution": {
     "iopub.execute_input": "2026-04-09T07:38:08.229289Z",
     "iopub.status.busy": "2026-04-09T07:38:08.228885Z",
     "iopub.status.idle": "2026-04-09T08:46:13.102027Z",
     "shell.execute_reply": "2026-04-09T08:46:13.101337Z"
    },
    "jupyter": {
     "outputs_hidden": false
    },
    "papermill": {
     "duration": 4084.882306,
     "end_time": "2026-04-09T08:46:13.107558+00:00",
     "exception": false,
     "start_time": "2026-04-09T07:38:08.225252+00:00",
     "status": "completed"
    },
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Đang kiểm thử Tổ hợp: ['Fp1', 'Fp2', 'F7', 'F3', 'Fz', 'F4', 'F8', 'T3', 'C3', 'Cz', 'C4', 'T4', 'T5', 'P3', 'Pz', 'P4', 'T6', 'O1', 'O2'] (Indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18])\n",
      "Sử dụng thiết bị: cuda\n",
      ">>> Đang tải dữ liệu từ 88 subjects...\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/tmp/ipykernel_24/3442735170.py:129: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.\n",
      "  df = pd.read_csv(tsv_path, sep=r'\\t')\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "===== Bắt đầu Training (Chế độ Voting: TẮT) =====\n",
      "\n",
      "===== Đang xử lý Fold 0 =====\n",
      ">>> Đang tải Ma trận Cấu trúc từ: /kaggle/input/notebooks/dtandat/mf-mgcn-processing/processed_data/structural_adjacency.csv\n",
      "    -> Tìm thấy 74 kết nối cấu trúc hợp lệ trên 19 kênh.\n",
      "Train Bệnh nhân: AD=23, NC=23\n",
      "+---------------------+---------------------------------+----------------+----------+\n",
      "| Layer               | Input Shape                     | Output Shape   | #Param   |\n",
      "|---------------------+---------------------------------+----------------+----------|\n",
      "| MaskedStructuralGAT | [608, 608]                      | [32, 2]        | 20,876   |\n",
      "| ├─(gat1)GATv2Conv   | [608, 8], [2, 2368], [2368, 1]  | [608, 16]      | 336      |\n",
      "| ├─(norm1)GraphNorm  | [608, 16]                       | [608, 16]      | 48       |\n",
      "| ├─(gat2)GATv2Conv   | [608, 16], [2, 2368], [2368, 1] | [608, 16]      | 592      |\n",
      "| ├─(norm2)GraphNorm  | [608, 16]                       | [608, 16]      | 48       |\n",
      "| ├─(fc1)Linear       | [32, 304]                       | [32, 64]       | 19,520   |\n",
      "| ├─(bn1)BatchNorm1d  | [32, 64]                        | [32, 64]       | 128      |\n",
      "| ├─(fc2)Linear       | [32, 64]                        | [32, 2]        | 130      |\n",
      "| ├─(dropout)Dropout  | [32, 64]                        | [32, 64]       | --       |\n",
      "+---------------------+---------------------------------+----------------+----------+\n",
      "Epoch 00 | Tr Loss: 0.4516 | Tr Acc: 0.8473 | Val Acc: 0.6355 | Best Val: 0.6355\n",
      "Epoch 10 | Tr Loss: 0.3090 | Tr Acc: 0.9423 | Val Acc: 0.8534 | Best Val: 0.8634\n",
      "Epoch 20 | Tr Loss: 0.3043 | Tr Acc: 0.9456 | Val Acc: 0.8368 | Best Val: 0.8714\n",
      "Epoch 30 | Tr Loss: 0.2897 | Tr Acc: 0.9570 | Val Acc: 0.8262 | Best Val: 0.8714\n",
      "Epoch 40 | Tr Loss: 0.2840 | Tr Acc: 0.9607 | Val Acc: 0.8345 | Best Val: 0.8714\n",
      "Epoch 50 | Tr Loss: 0.2722 | Tr Acc: 0.9683 | Val Acc: 0.8233 | Best Val: 0.8714\n",
      "Epoch 60 | Tr Loss: 0.2708 | Tr Acc: 0.9683 | Val Acc: 0.8293 | Best Val: 0.8714\n",
      "Epoch 70 | Tr Loss: 0.2689 | Tr Acc: 0.9691 | Val Acc: 0.8288 | Best Val: 0.8714\n",
      "Epoch 80 | Tr Loss: 0.2676 | Tr Acc: 0.9697 | Val Acc: 0.8308 | Best Val: 0.8714\n",
      "Epoch 90 | Tr Loss: 0.2684 | Tr Acc: 0.9715 | Val Acc: 0.8242 | Best Val: 0.8714\n",
      "Epoch 99 | Tr Loss: 0.2688 | Tr Acc: 0.9700 | Val Acc: 0.8179 | Best Val: 0.8714\n",
      "\n",
      "===== Đang xử lý Fold 1 =====\n",
      ">>> Đang tải Ma trận Cấu trúc từ: /kaggle/input/notebooks/dtandat/mf-mgcn-processing/processed_data/structural_adjacency.csv\n",
      "    -> Tìm thấy 74 kết nối cấu trúc hợp lệ trên 19 kênh.\n",
      "Train Bệnh nhân: AD=29, NC=23\n",
      "Epoch 00 | Tr Loss: 0.5100 | Tr Acc: 0.7793 | Val Acc: 0.7256 | Best Val: 0.7256\n",
      "Epoch 10 | Tr Loss: 0.3566 | Tr Acc: 0.9122 | Val Acc: 0.8232 | Best Val: 0.8879\n",
      "Epoch 20 | Tr Loss: 0.3316 | Tr Acc: 0.9299 | Val Acc: 0.8054 | Best Val: 0.8879\n",
      "Epoch 30 | Tr Loss: 0.3203 | Tr Acc: 0.9355 | Val Acc: 0.8158 | Best Val: 0.8879\n",
      "Epoch 40 | Tr Loss: 0.3152 | Tr Acc: 0.9389 | Val Acc: 0.7954 | Best Val: 0.8879\n",
      "Epoch 50 | Tr Loss: 0.3122 | Tr Acc: 0.9420 | Val Acc: 0.7840 | Best Val: 0.8879\n",
      "Epoch 60 | Tr Loss: 0.3098 | Tr Acc: 0.9440 | Val Acc: 0.7883 | Best Val: 0.8879\n",
      "Epoch 70 | Tr Loss: 0.3044 | Tr Acc: 0.9484 | Val Acc: 0.7967 | Best Val: 0.8879\n",
      "Epoch 80 | Tr Loss: 0.3063 | Tr Acc: 0.9462 | Val Acc: 0.7983 | Best Val: 0.8879\n",
      "Epoch 90 | Tr Loss: 0.3023 | Tr Acc: 0.9486 | Val Acc: 0.7880 | Best Val: 0.8879\n",
      "Epoch 99 | Tr Loss: 0.3043 | Tr Acc: 0.9473 | Val Acc: 0.7914 | Best Val: 0.8879\n",
      "\n",
      "===== Đang xử lý Fold 2 =====\n",
      ">>> Đang tải Ma trận Cấu trúc từ: /kaggle/input/notebooks/dtandat/mf-mgcn-processing/processed_data/structural_adjacency.csv\n",
      "    -> Tìm thấy 74 kết nối cấu trúc hợp lệ trên 19 kênh.\n",
      "Train Bệnh nhân: AD=29, NC=23\n",
      "Epoch 00 | Tr Loss: 0.4942 | Tr Acc: 0.7908 | Val Acc: 0.6289 | Best Val: 0.6289\n",
      "Epoch 10 | Tr Loss: 0.3575 | Tr Acc: 0.9090 | Val Acc: 0.7658 | Best Val: 0.7912\n",
      "Epoch 20 | Tr Loss: 0.3261 | Tr Acc: 0.9317 | Val Acc: 0.6905 | Best Val: 0.7912\n",
      "Epoch 30 | Tr Loss: 0.3194 | Tr Acc: 0.9360 | Val Acc: 0.6474 | Best Val: 0.7912\n",
      "Epoch 40 | Tr Loss: 0.3119 | Tr Acc: 0.9448 | Val Acc: 0.6101 | Best Val: 0.7912\n",
      "Epoch 50 | Tr Loss: 0.3086 | Tr Acc: 0.9446 | Val Acc: 0.6347 | Best Val: 0.7912\n",
      "Epoch 60 | Tr Loss: 0.3080 | Tr Acc: 0.9453 | Val Acc: 0.6368 | Best Val: 0.7912\n",
      "Epoch 70 | Tr Loss: 0.3032 | Tr Acc: 0.9487 | Val Acc: 0.6024 | Best Val: 0.7912\n",
      "Epoch 80 | Tr Loss: 0.3041 | Tr Acc: 0.9485 | Val Acc: 0.5913 | Best Val: 0.7912\n",
      "Epoch 90 | Tr Loss: 0.3045 | Tr Acc: 0.9491 | Val Acc: 0.6051 | Best Val: 0.7912\n",
      "Epoch 99 | Tr Loss: 0.3031 | Tr Acc: 0.9489 | Val Acc: 0.5979 | Best Val: 0.7912\n",
      "\n",
      "===== Đang xử lý Fold 3 =====\n",
      ">>> Đang tải Ma trận Cấu trúc từ: /kaggle/input/notebooks/dtandat/mf-mgcn-processing/processed_data/structural_adjacency.csv\n",
      "    -> Tìm thấy 74 kết nối cấu trúc hợp lệ trên 19 kênh.\n",
      "Train Bệnh nhân: AD=29, NC=24\n",
      "Epoch 00 | Tr Loss: 0.4960 | Tr Acc: 0.7994 | Val Acc: 0.6048 | Best Val: 0.6048\n",
      "Epoch 10 | Tr Loss: 0.3453 | Tr Acc: 0.9199 | Val Acc: 0.7099 | Best Val: 0.7804\n",
      "Epoch 20 | Tr Loss: 0.3212 | Tr Acc: 0.9359 | Val Acc: 0.6747 | Best Val: 0.7804\n",
      "Epoch 30 | Tr Loss: 0.3133 | Tr Acc: 0.9435 | Val Acc: 0.6558 | Best Val: 0.7804\n",
      "Epoch 40 | Tr Loss: 0.3113 | Tr Acc: 0.9439 | Val Acc: 0.6687 | Best Val: 0.7804\n",
      "Epoch 50 | Tr Loss: 0.3028 | Tr Acc: 0.9483 | Val Acc: 0.6257 | Best Val: 0.7804\n",
      "Epoch 60 | Tr Loss: 0.2956 | Tr Acc: 0.9523 | Val Acc: 0.6286 | Best Val: 0.7804\n",
      "Epoch 70 | Tr Loss: 0.2980 | Tr Acc: 0.9512 | Val Acc: 0.6203 | Best Val: 0.7804\n",
      "Epoch 80 | Tr Loss: 0.2959 | Tr Acc: 0.9525 | Val Acc: 0.6154 | Best Val: 0.7804\n",
      "Epoch 90 | Tr Loss: 0.2958 | Tr Acc: 0.9553 | Val Acc: 0.6200 | Best Val: 0.7804\n",
      "Epoch 99 | Tr Loss: 0.2963 | Tr Acc: 0.9521 | Val Acc: 0.6269 | Best Val: 0.7804\n",
      "\n",
      "===== Đang xử lý Fold 4 =====\n",
      ">>> Đang tải Ma trận Cấu trúc từ: /kaggle/input/notebooks/dtandat/mf-mgcn-processing/processed_data/structural_adjacency.csv\n",
      "    -> Tìm thấy 74 kết nối cấu trúc hợp lệ trên 19 kênh.\n",
      "Train Bệnh nhân: AD=29, NC=23\n",
      "Epoch 00 | Tr Loss: 0.4953 | Tr Acc: 0.8026 | Val Acc: 0.6712 | Best Val: 0.6712\n",
      "Epoch 10 | Tr Loss: 0.3633 | Tr Acc: 0.9090 | Val Acc: 0.7256 | Best Val: 0.8300\n",
      "Epoch 20 | Tr Loss: 0.3388 | Tr Acc: 0.9236 | Val Acc: 0.8335 | Best Val: 0.8335\n",
      "Epoch 30 | Tr Loss: 0.3357 | Tr Acc: 0.9268 | Val Acc: 0.7988 | Best Val: 0.8559\n",
      "Epoch 40 | Tr Loss: 0.3220 | Tr Acc: 0.9362 | Val Acc: 0.8052 | Best Val: 0.8559\n",
      "Epoch 50 | Tr Loss: 0.3193 | Tr Acc: 0.9350 | Val Acc: 0.7914 | Best Val: 0.8559\n",
      "Epoch 60 | Tr Loss: 0.3156 | Tr Acc: 0.9387 | Val Acc: 0.7943 | Best Val: 0.8559\n",
      "Epoch 70 | Tr Loss: 0.3126 | Tr Acc: 0.9425 | Val Acc: 0.7764 | Best Val: 0.8559\n",
      "Epoch 80 | Tr Loss: 0.3111 | Tr Acc: 0.9428 | Val Acc: 0.7854 | Best Val: 0.8559\n",
      "Epoch 90 | Tr Loss: 0.3130 | Tr Acc: 0.9412 | Val Acc: 0.7888 | Best Val: 0.8559\n",
      "Epoch 99 | Tr Loss: 0.3091 | Tr Acc: 0.9438 | Val Acc: 0.7827 | Best Val: 0.8559\n",
      "\n",
      "===== Đang xử lý Fold 5 =====\n",
      ">>> Đang tải Ma trận Cấu trúc từ: /kaggle/input/notebooks/dtandat/mf-mgcn-processing/processed_data/structural_adjacency.csv\n",
      "    -> Tìm thấy 74 kết nối cấu trúc hợp lệ trên 19 kênh.\n",
      "Train Bệnh nhân: AD=29, NC=23\n",
      "Epoch 00 | Tr Loss: 0.4603 | Tr Acc: 0.8257 | Val Acc: 0.6305 | Best Val: 0.6305\n",
      "Epoch 10 | Tr Loss: 0.3416 | Tr Acc: 0.9220 | Val Acc: 0.6151 | Best Val: 0.6680\n",
      "Epoch 20 | Tr Loss: 0.3212 | Tr Acc: 0.9337 | Val Acc: 0.5908 | Best Val: 0.6680\n",
      "Epoch 30 | Tr Loss: 0.3129 | Tr Acc: 0.9399 | Val Acc: 0.5913 | Best Val: 0.6680\n",
      "Epoch 40 | Tr Loss: 0.3017 | Tr Acc: 0.9492 | Val Acc: 0.6096 | Best Val: 0.6680\n",
      "Epoch 50 | Tr Loss: 0.2974 | Tr Acc: 0.9551 | Val Acc: 0.5919 | Best Val: 0.6680\n",
      "Epoch 60 | Tr Loss: 0.2945 | Tr Acc: 0.9549 | Val Acc: 0.5929 | Best Val: 0.6680\n",
      "Epoch 70 | Tr Loss: 0.2932 | Tr Acc: 0.9555 | Val Acc: 0.5956 | Best Val: 0.6680\n",
      "Epoch 80 | Tr Loss: 0.2898 | Tr Acc: 0.9581 | Val Acc: 0.5977 | Best Val: 0.6680\n",
      "Epoch 90 | Tr Loss: 0.2906 | Tr Acc: 0.9574 | Val Acc: 0.5942 | Best Val: 0.6680\n",
      "Epoch 99 | Tr Loss: 0.2924 | Tr Acc: 0.9561 | Val Acc: 0.6030 | Best Val: 0.6680\n",
      "\n",
      "===== Đang xử lý Fold 6 =====\n",
      ">>> Đang tải Ma trận Cấu trúc từ: /kaggle/input/notebooks/dtandat/mf-mgcn-processing/processed_data/structural_adjacency.csv\n",
      "    -> Tìm thấy 74 kết nối cấu trúc hợp lệ trên 19 kênh.\n",
      "Train Bệnh nhân: AD=29, NC=23\n",
      "Epoch 00 | Tr Loss: 0.5098 | Tr Acc: 0.7814 | Val Acc: 0.6611 | Best Val: 0.6611\n",
      "Epoch 10 | Tr Loss: 0.3531 | Tr Acc: 0.9124 | Val Acc: 0.7811 | Best Val: 0.8345\n",
      "Epoch 20 | Tr Loss: 0.3466 | Tr Acc: 0.9177 | Val Acc: 0.8493 | Best Val: 0.8499\n",
      "Epoch 30 | Tr Loss: 0.3391 | Tr Acc: 0.9242 | Val Acc: 0.7724 | Best Val: 0.8694\n",
      "Epoch 40 | Tr Loss: 0.3227 | Tr Acc: 0.9338 | Val Acc: 0.7655 | Best Val: 0.8694\n",
      "Epoch 50 | Tr Loss: 0.3108 | Tr Acc: 0.9434 | Val Acc: 0.7978 | Best Val: 0.8694\n",
      "Epoch 60 | Tr Loss: 0.3080 | Tr Acc: 0.9450 | Val Acc: 0.8054 | Best Val: 0.8694\n",
      "Epoch 70 | Tr Loss: 0.3008 | Tr Acc: 0.9489 | Val Acc: 0.7973 | Best Val: 0.8694\n",
      "Epoch 80 | Tr Loss: 0.3025 | Tr Acc: 0.9482 | Val Acc: 0.7973 | Best Val: 0.8694\n",
      "Epoch 90 | Tr Loss: 0.2970 | Tr Acc: 0.9520 | Val Acc: 0.7898 | Best Val: 0.8694\n",
      "Epoch 99 | Tr Loss: 0.2992 | Tr Acc: 0.9516 | Val Acc: 0.8031 | Best Val: 0.8694\n",
      "\n",
      ">>> TRUNG BÌNH K-FOLD ACCURACY (Tổ hợp ['Fp1', 'Fp2', 'F7', 'F3', 'Fz', 'F4', 'F8', 'T3', 'C3', 'Cz', 'C4', 'T4', 'T5', 'P3', 'Pz', 'P4', 'T6', 'O1', 'O2']): 0.8177\n"
     ]
    }
   ],
   "source": [
    "import torch\n",
    "import torch.nn as nn\n",
    "import torch.nn.functional as F\n",
    "import os\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import random\n",
    "from sklearn.preprocessing import StandardScaler\n",
    "from sklearn.metrics import f1_score, accuracy_score, recall_score, confusion_matrix\n",
    "import sys\n",
    "from collections import defaultdict\n",
    "import csv\n",
    "import gc\n",
    "from torch_geometric.nn import GATv2Conv, BatchNorm\n",
    "from torch_geometric.nn import global_mean_pool, global_max_pool\n",
    "from torch_geometric.nn.norm import GraphNorm\n",
    "from torch_geometric.data import Data\n",
    "from torch_geometric.loader import DataLoader\n",
    "from torch_geometric.nn import summary\n",
    "\n",
    "# =====================================================================\n",
    "# CẤU HÌNH HỆ THỐNG\n",
    "# =====================================================================\n",
    "USE_MAJORITY_VOTING = False  # Đổi thành True để dùng Voting cấp độ bệnh nhân\n",
    "NUM_FEATURES = 8             # Số đặc trưng mỗi nút (5 PSD + 3 Hjorth)\n",
    "\n",
    "ALL_19_CHANNELS = [\n",
    "    'Fp1', 'Fp2', 'F7', 'F3', 'Fz', 'F4', 'F8', \n",
    "    'T3', 'C3', 'Cz', 'C4', 'T4', 'T5', 'P3', \n",
    "    'Pz', 'P4', 'T6', 'O1', 'O2'\n",
    "]\n",
    "\n",
    "def seed_everything(seed=42):\n",
    "    random.seed(seed)\n",
    "    np.random.seed(seed)\n",
    "    torch.manual_seed(seed)\n",
    "\n",
    "# =====================================================================\n",
    "# KIẾN TRÚC AI SOTA: DYNAMIC GRAPH TRANSFORMER (DÀNH CHO 3 KÊNH)\n",
    "# =====================================================================\n",
    "class MaskedStructuralGAT(nn.Module):\n",
    "    def __init__(self, num_nodes=19, num_edges=None, in_features=NUM_FEATURES, num_classes=2):\n",
    "        super(MaskedStructuralGAT, self).__init__()\n",
    "        self.num_nodes = num_nodes\n",
    "        \n",
    "        # [QUAN TRỌNG] Tham số học trọng số cạnh giờ chỉ bằng đúng số cạnh thực tế (Ví dụ: 40 cạnh thay vì 342)\n",
    "        # Điều này triệt tiêu hoàn toàn khả năng mạng \"vẽ\" ra các kết nối nhiễu.\n",
    "        self.edge_weight_param = nn.Parameter(torch.ones(num_edges, 1))\n",
    "        \n",
    "        # Lớp GAT Nút Cổ Chai (Bottleneck)\n",
    "        self.gat1 = GATv2Conv(in_features, 4, heads=4, concat=True, edge_dim=1, dropout=0.5)\n",
    "        self.norm1 = GraphNorm(16)\n",
    "        \n",
    "        self.gat2 = GATv2Conv(16, 8, heads=2, concat=True, edge_dim=1, dropout=0.5)\n",
    "        self.norm2 = GraphNorm(16)\n",
    "        \n",
    "        self.flattened_size = num_nodes * 16\n",
    "        \n",
    "        # MLP Phân loại\n",
    "        self.fc1 = nn.Linear(self.flattened_size, 64)\n",
    "        self.bn1 = nn.BatchNorm1d(64)\n",
    "        self.fc2 = nn.Linear(64, num_classes)\n",
    "        \n",
    "        self.dropout = nn.Dropout(p=0.5)\n",
    "\n",
    "    def forward(self, data):\n",
    "        x, edge_index = data.x, data.edge_index\n",
    "        num_graphs = data.num_graphs\n",
    "        \n",
    "        # Điều chỉnh trọng số cạnh dựa trên ma trận tiên nghiệm thay vì học ngẫu nhiên\n",
    "        dynamic_edge_attr = torch.sigmoid(self.edge_weight_param.repeat(num_graphs, 1))\n",
    "\n",
    "        x = self.gat1(x, edge_index, dynamic_edge_attr)\n",
    "        x = self.norm1(x)\n",
    "        x = F.leaky_relu(x, negative_slope=0.2)\n",
    "        \n",
    "        x = self.gat2(x, edge_index, dynamic_edge_attr)\n",
    "        x = self.norm2(x)\n",
    "        x = F.leaky_relu(x, negative_slope=0.2)\n",
    "        \n",
    "        x_flattened = x.view(num_graphs, self.flattened_size)\n",
    "\n",
    "        x = self.fc1(x_flattened)\n",
    "        x = self.bn1(x)\n",
    "        x = F.leaky_relu(x, negative_slope=0.2)\n",
    "        x = self.dropout(x)\n",
    "        \n",
    "        logits = self.fc2(x)\n",
    "        return logits\n",
    "\n",
    "# =====================================================================\n",
    "# HÀM XỬ LÝ DỮ LIỆU & BATCHING\n",
    "# =====================================================================\n",
    "def load_structural_prior(csv_path):\n",
    "    print(f\">>> Đang tải Ma trận Cấu trúc từ: {csv_path}\")\n",
    "    \n",
    "    # Đọc file CSV. Tùy thuộc vào file của bạn có header hay không, bạn có thể chỉnh sửa `header`\n",
    "    try:\n",
    "        # Nếu file có tên cột/hàng (VD: Fp1, Fp2...)\n",
    "        df = pd.read_csv(csv_path, index_col=0)\n",
    "        adj_matrix = df.values\n",
    "    except:\n",
    "        # Nếu file chỉ là ma trận số thuần túy\n",
    "        df = pd.read_csv(csv_path, header=None)\n",
    "        adj_matrix = df.values\n",
    "\n",
    "    # Ép về float32 để tương thích với PyTorch\n",
    "    adj_matrix = np.nan_to_num(adj_matrix, nan=0.0).astype(np.float32)\n",
    "    \n",
    "    # Tìm tọa độ của các cạnh có kết nối (giá trị > 0)\n",
    "    sources, targets = np.where(adj_matrix > 0)\n",
    "    \n",
    "    # Tạo edge_index cho PyTorch Geometric\n",
    "    edge_index = torch.tensor(np.vstack((sources, targets)), dtype=torch.long)\n",
    "    \n",
    "    # Lấy trọng số khởi tạo của cấu trúc não (nếu file CSV chỉ chứa 0 và 1 thì đây sẽ là mảng toàn 1)\n",
    "    edge_attr = torch.tensor(adj_matrix[sources, targets], dtype=torch.float32).unsqueeze(1)\n",
    "    \n",
    "    print(f\"    -> Tìm thấy {edge_index.shape[1]} kết nối cấu trúc hợp lệ trên 19 kênh.\")\n",
    "    return edge_index, edge_attr\n",
    "    \n",
    "def load_raw_data_dict():\n",
    "    BASE_DIR_01 = '/kaggle/input/notebooks/dtandat/mf-mgcn-processing'\n",
    "    PROCESSED_DIR = os.path.join(BASE_DIR_01, \"processed_data\")\n",
    "    BASE_DIR_02 = '/kaggle/input/datasets/dtandat/mf-mgcn-datasets/ds004504'\n",
    "    tsv_path = os.path.join(BASE_DIR_02, \"participants.tsv\")\n",
    "\n",
    "    try:\n",
    "        df = pd.read_csv(tsv_path, sep=r'\\t')\n",
    "    except:\n",
    "        df = pd.read_csv(tsv_path, sep=r'\\s+')\n",
    "    \n",
    "    sub_label_map = {}\n",
    "    for _, row in df.iterrows():\n",
    "        sub = row['participant_id']\n",
    "        grp = str(row['Group']).strip()\n",
    "        if grp == 'A': sub_label_map[sub] = 'AD'\n",
    "        elif grp == 'C': sub_label_map[sub] = 'NC'\n",
    "    \n",
    "    raw_data_dict = {'AD':[], 'NC':[]}\n",
    "    files = sorted([f for f in os.listdir(PROCESSED_DIR) if f.endswith('_features.npy')])\n",
    "    \n",
    "    print(f\">>> Đang tải dữ liệu từ {len(files)} subjects...\")\n",
    "    for f in files:\n",
    "        sub_id = f.split('_')[0]\n",
    "        if sub_id not in sub_label_map: continue\n",
    "        \n",
    "        features_raw = np.load(os.path.join(PROCESSED_DIR, f))\n",
    "        features_raw = np.nan_to_num(features_raw, nan=0.0)\n",
    "        raw_data_dict[sub_label_map[sub_id]].append({\n",
    "            'features': features_raw,\n",
    "            'id': sub_id\n",
    "        })\n",
    "    \n",
    "    return raw_data_dict\n",
    "\n",
    "def create_dataloaders(raw_data_dict, combo_indices, train_indices, val_indices, batch_size=32):\n",
    "    scaler = StandardScaler()\n",
    "    ad_list, nc_list = raw_data_dict['AD'], raw_data_dict['NC']\n",
    "    ad_ids = {item['id'] for item in ad_list}\n",
    "    \n",
    "    def get_subs(indices, source_list):\n",
    "        return [source_list[i] for i in indices if i < len(source_list)]\n",
    "    \n",
    "    train_subs = get_subs(train_indices['AD'], ad_list) + get_subs(train_indices['NC'], nc_list)\n",
    "    val_subs = get_subs(val_indices['AD'], ad_list) + get_subs(val_indices['NC'], nc_list)\n",
    "\n",
    "    if not train_subs: return None, None, 0, 0\n",
    "\n",
    "    # [SỬA LỖI TẠI ĐÂY] Gom toàn bộ dữ liệu Train và duỗi thành 2D\n",
    "    all_train_data = np.vstack([sub['features'] for sub in train_subs])\n",
    "    # all_train_data đang có shape: (Tổng số đoạn, 19, 8) -> Ép về: (Tổng số đoạn * 19, 8)\n",
    "    all_train_data_2d = all_train_data.reshape(-1, NUM_FEATURES)\n",
    "    scaler.fit(all_train_data_2d)\n",
    "\n",
    "    # Khởi tạo đồ thị 3 Nút (9 Cạnh Fully Connected) cho GATv2\n",
    "    # [ĐÃ SỬA] Khởi tạo đồ thị Fully Connected cho 19 Nút\n",
    "    num_nodes = len(combo_indices) # 19\n",
    "    edges = [[i, j] for i in range(num_nodes) for j in range(num_nodes) if i != j] # Bỏ self-loop ban đầu, PyG sẽ tự thêm\n",
    "    edge_index = torch.tensor(edges, dtype=torch.long).t().contiguous()\n",
    "    \n",
    "    # Khởi tạo edge_attr ban đầu bằng 1.0 (Mô hình sẽ tự học điều chỉnh sau)\n",
    "    edge_attr = torch.ones((edge_index.shape[1], 1), dtype=torch.float32)\n",
    "\n",
    "    CSV_PATH = '/kaggle/input/notebooks/dtandat/mf-mgcn-processing/processed_data/structural_adjacency.csv'\n",
    "    global_edge_index, global_edge_attr = load_structural_prior(CSV_PATH)\n",
    "    num_edges = global_edge_index.shape[1]\n",
    "    \n",
    "    def convert_to_pyg(sub_list):\n",
    "        data_list = []\n",
    "        cnt_0, cnt_1 = 0, 0\n",
    "        \n",
    "        for sub in sub_list:\n",
    "            sub_feats = sub['features']\n",
    "            n_segs = sub_feats.shape[0]\n",
    "            \n",
    "            # [SỬA LỖI TẠI ĐÂY] Duỗi thành 2D để transform, sau đó gấp lại thành 3D\n",
    "            sub_feats_2d = sub_feats.reshape(-1, NUM_FEATURES)\n",
    "            feats_scaled_2d = np.nan_to_num(scaler.transform(sub_feats_2d))\n",
    "            \n",
    "            # Khôi phục shape gốc (Epochs, 19 Kênh, 8 Đặc trưng)\n",
    "            features_3d = feats_scaled_2d.reshape(n_segs, 19, NUM_FEATURES)\n",
    "            \n",
    "            # [SLICE] Cắt lấy đúng 3 kênh đang xét (Sức mạnh của vét cạn nằm ở đây)\n",
    "            features_3d_subset = features_3d[:, combo_indices, :]\n",
    "            \n",
    "            y_label = 0 if sub['id'] in ad_ids else 1\n",
    "            if y_label == 0: cnt_0 += 1\n",
    "            else: cnt_1 += 1\n",
    "\n",
    "            for i in range(n_segs):\n",
    "                x = torch.tensor(features_3d_subset[i], dtype=torch.float32)\n",
    "                y = torch.tensor([y_label], dtype=torch.long)\n",
    "                \n",
    "                # Gán edge_index và edge_attr từ file CSV thay vì đồ thị tĩnh\n",
    "                data = Data(x=x, y=y, edge_index=global_edge_index, edge_attr=global_edge_attr, sub_id=sub['id'])\n",
    "                data_list.append(data)\n",
    "                \n",
    "        return data_list, cnt_0, cnt_1, num_edges\n",
    "    \n",
    "    train_data, t_cnt_0, t_cnt_1, num_edges = convert_to_pyg(train_subs)\n",
    "    val_data, _, _, _ = convert_to_pyg(val_subs)\n",
    "    \n",
    "    print(f\"Train Bệnh nhân: AD={t_cnt_0}, NC={t_cnt_1}\")\n",
    "\n",
    "    train_loader = DataLoader(train_data, batch_size=batch_size, shuffle=True)\n",
    "    val_loader = DataLoader(val_data, batch_size=batch_size, shuffle=False)\n",
    "    \n",
    "    return train_loader, val_loader, t_cnt_0, t_cnt_1, num_edges\n",
    "\n",
    "# =====================================================================\n",
    "# VÒNG LẶP HUẤN LUYỆN & ĐÁNH GIÁ\n",
    "# =====================================================================\n",
    "def train_epoch(model, loader, criterion, optimizer, device):\n",
    "    model.train()\n",
    "    total_loss, total_correct, total_samples = 0, 0, 0\n",
    "    \n",
    "    for data in loader:\n",
    "        data = data.to(device)\n",
    "        optimizer.zero_grad()\n",
    "        out = model(data)\n",
    "        loss = criterion(out, data.y)\n",
    "        loss.backward()\n",
    "        optimizer.step()\n",
    "\n",
    "        total_loss += loss.item() * data.num_graphs\n",
    "        total_correct += (out.argmax(dim=1) == data.y).sum().item()\n",
    "        total_samples += data.num_graphs\n",
    "\n",
    "    return total_loss / total_samples, total_correct / total_samples\n",
    "\n",
    "def evaluate(model, loader, criterion, device):\n",
    "    model.eval()\n",
    "    \n",
    "    if USE_MAJORITY_VOTING:\n",
    "        # CHẤM ĐIỂM THEO MAJORITY VOTING (SUBJECT-LEVEL)\n",
    "        patient_preds = defaultdict(list)\n",
    "        patient_trues = defaultdict(int)\n",
    "        total_samples, total_loss = 0, 0\n",
    "\n",
    "        with torch.no_grad():\n",
    "            for data in loader:\n",
    "                data = data.to(device)\n",
    "                out = model(data)\n",
    "                loss = criterion(out, data.y)\n",
    "                preds = out.argmax(dim=1).cpu().tolist()\n",
    "                trues = data.y.cpu().tolist()\n",
    "                sub_ids = data.sub_id\n",
    "                \n",
    "                total_loss += loss.item() * data.num_graphs\n",
    "                total_samples += data.num_graphs\n",
    "                \n",
    "                for i in range(len(sub_ids)):\n",
    "                    sub_id = sub_ids[i]\n",
    "                    patient_preds[sub_id].append(preds[i])\n",
    "                    patient_trues[sub_id] = trues[i]\n",
    "        \n",
    "        final_preds, final_trues = [], []\n",
    "        for sub_id, preds_list in patient_preds.items():\n",
    "            count_0 = preds_list.count(0)\n",
    "            count_1 = preds_list.count(1)\n",
    "            final_vote = 1 if count_1 > count_0 else 0\n",
    "            final_preds.append(final_vote)\n",
    "            final_trues.append(patient_trues[sub_id])\n",
    "\n",
    "        loss = total_loss / total_samples\n",
    "        acc = accuracy_score(final_trues, final_preds)\n",
    "        f1 = f1_score(final_trues, final_preds, average='macro', zero_division=0)\n",
    "        recall = recall_score(final_trues, final_preds, average='macro', zero_division=0)\n",
    "        \n",
    "    else:\n",
    "        # CHẤM ĐIỂM THEO ĐOẠN (SEGMENT-LEVEL)\n",
    "        total_correct, total_samples, total_loss = 0, 0, 0\n",
    "        all_targets, all_preds = [], []\n",
    "        \n",
    "        with torch.no_grad():\n",
    "            for data in loader:\n",
    "                data = data.to(device)\n",
    "                out = model(data)\n",
    "                loss = criterion(out, data.y)\n",
    "                pred = out.argmax(dim=1)\n",
    "                \n",
    "                total_loss += loss.item() * data.num_graphs\n",
    "                total_correct += (pred == data.y).sum().item()\n",
    "                total_samples += data.num_graphs\n",
    "                \n",
    "                all_targets.extend(data.y.cpu().tolist())\n",
    "                all_preds.extend(pred.cpu().tolist())\n",
    "            \n",
    "        acc = total_correct / total_samples\n",
    "        loss = total_loss / total_samples\n",
    "        f1 = f1_score(all_targets, all_preds, average='macro', zero_division=0)\n",
    "        recall = recall_score(all_targets, all_preds, average='macro', zero_division=0)\n",
    "\n",
    "    return acc, f1, recall, loss\n",
    "\n",
    "def main():\n",
    "    # Nhận 3 kênh từ Terminal (VD: python train.py Fp1 F8 Pz)\n",
    "    # INPUT_CHANNELS = sys.argv[1:]\n",
    "    INPUT_CHANNELS = [\n",
    "    'Fp1', 'Fp2', 'F7', 'F3', 'Fz', 'F4', 'F8', \n",
    "    'T3', 'C3', 'Cz', 'C4', 'T4', 'T5', 'P3', \n",
    "    'Pz', 'P4', 'T6', 'O1', 'O2'\n",
    "    ]\n",
    "    if len(INPUT_CHANNELS) != 19:\n",
    "        print(\"Vui lòng truyền đúng 3 kênh. VD: python train.py Fp1 F8 Pz\")\n",
    "        sys.exit(1)\n",
    "        \n",
    "    # Ánh xạ tên kênh thành Index (0-18)\n",
    "    combo_indices = [ALL_19_CHANNELS.index(ch) for ch in INPUT_CHANNELS]\n",
    "    print(f\"Đang kiểm thử Tổ hợp: {INPUT_CHANNELS} (Indices: {combo_indices})\")\n",
    "\n",
    "    seed_everything(42)\n",
    "    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')\n",
    "    print(f\"Sử dụng thiết bị: {device}\")\n",
    "\n",
    "    raw_data_dict = load_raw_data_dict()\n",
    "\n",
    "    folds_indices = [        \n",
    "        ([21, 2, 24, 11, 19, 30, 14, 35, 27, 0, 3, 10, 6, 12, 31, 4, 32, 25, 33, 13, 7, 28, 26], [15, 22, 20, 34, 16, 29], [17, 25, 19, 0, 3, 16, 10, 6, 12, 2, 4, 22, 13, 7, 9, 18, 28, 8, 1, 5, 23, 14, 26], [11, 21, 27, 15, 20, 24]),\n",
    "        ([18, 35, 32, 11, 2, 7, 5, 4, 22, 25, 13, 14, 6, 21, 26, 29, 9, 19, 1, 23, 12, 17, 20, 24, 15, 10, 31, 30, 0], [34, 16, 3, 28, 27, 33, 8], [8, 13, 5, 4, 21, 23, 16, 28, 14, 6, 22, 18, 9, 19, 1, 12, 17, 20, 24, 15, 10, 0, 7], [11, 3, 27, 26, 25, 2]),\n",
    "        ([0, 1, 3, 4, 5, 7, 8, 9, 11, 12, 13, 14, 16, 17, 18, 19, 20, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 33, 35], [2, 6, 10, 15, 21, 32, 34], [0, 2, 3, 4, 5, 6, 7, 8, 9, 11, 12, 13, 14, 17, 18, 19, 21, 22, 23, 24, 25, 26, 28], [1, 10, 15, 16, 20, 27]),\n",
    "        ([1, 2, 3, 4, 5, 6, 8, 9, 10, 11, 12, 14, 15, 18, 19, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 34, 35], [0, 7, 13, 16, 17, 20, 33], [0, 1, 3, 4, 5, 6, 7, 8, 10, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 26, 27, 28], [2, 9, 11, 24, 25]),\n",
    "        ([1, 2, 5, 7, 8, 9, 10, 11, 12, 13, 14, 15, 17, 18, 19, 20, 21, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 34, 35], [0, 3, 4, 6, 16, 22, 33], [0, 1, 3, 4, 5, 6, 8, 10, 11, 12, 14, 15, 16, 17, 18, 19, 21, 22, 23, 24, 25, 26, 28], [2, 7, 9, 13, 20, 27]),\n",
    "        ([15, 22, 17, 20, 34, 16, 29, 35, 27, 0, 3, 10, 6, 12, 31, 4, 32, 25, 33, 13, 7, 28, 26, 9, 18, 8, 23, 1, 5], [21, 2, 24, 11, 19, 30, 14], [11, 21, 27, 15, 20, 24, 10, 6, 12, 2, 4, 22, 13, 7, 9, 18, 28, 8, 1, 5, 23, 14, 26], [17, 25, 19, 0, 3, 16]),\n",
    "        ([15, 22, 17, 20, 34, 16, 29, 21, 2, 24, 11, 19, 30, 14, 31, 4, 32, 25, 33, 13, 7, 28, 26, 9, 18, 8, 23, 1, 5], [35, 27, 0, 3, 10, 6, 12], [11, 21, 27, 15, 20, 24, 17, 25, 19, 0, 3, 16, 13, 7, 9, 18, 28, 8, 1, 5, 23, 14, 26], [10, 6, 12, 2, 4, 22])\n",
    "    ]\n",
    "\n",
    "    print(f\"===== Bắt đầu Training (Chế độ Voting: {'BẬT' if USE_MAJORITY_VOTING else 'TẮT'}) =====\")\n",
    "    best_vals = []\n",
    "    \n",
    "    for fold_idx, (tr_ad, val_ad, tr_nc, val_nc) in enumerate(folds_indices):\n",
    "        print(f\"\\n===== Đang xử lý Fold {fold_idx} =====\")\n",
    "        \n",
    "        train_loader, val_loader, t_cnt_0, t_cnt_1, num_edges = create_dataloaders(\n",
    "            raw_data_dict, combo_indices,\n",
    "            {'AD': tr_ad, 'NC': tr_nc},\n",
    "            {'AD': val_ad, 'NC': val_nc}\n",
    "        )\n",
    "\n",
    "        # Khởi tạo mô hình Masked GAT với đúng số lượng cạnh vật lý\n",
    "        model = MaskedStructuralGAT(num_nodes=19, num_edges=num_edges).to(device)\n",
    "        \n",
    "        # In tóm tắt mô hình ở Fold 0\n",
    "        if fold_idx == 0:\n",
    "            dummy_data = next(iter(train_loader)).to(device)\n",
    "            try: print(summary(model, dummy_data))\n",
    "            except Exception as e: pass\n",
    "\n",
    "        optimizer = torch.optim.Adam(model.parameters(), lr=0.001, weight_decay=5e-3)\n",
    "        scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode='max', factor=0.5, patience=10)\n",
    "        \n",
    "        # Tự động tính trọng số cân bằng lớp (Class Imbalance Weights)\n",
    "        weights = torch.tensor([1.0 / t_cnt_0, 1.0 / t_cnt_1], dtype=torch.float32).to(device)\n",
    "        weights = weights / weights.sum() \n",
    "        criterion = nn.CrossEntropyLoss(weight=weights, label_smoothing=0.1)\n",
    "\n",
    "        best_acc = 0.0\n",
    "        for epoch in range(100):\n",
    "            t_loss, t_acc = train_epoch(model, train_loader, criterion, optimizer, device)\n",
    "            v_acc, v_f1, v_recall, v_loss = evaluate(model, val_loader, criterion, device)\n",
    "            scheduler.step(v_acc)\n",
    "            \n",
    "            if v_acc > best_acc: best_acc = v_acc\n",
    "            \n",
    "            if epoch % 10 == 0 or epoch == 99:\n",
    "                lr = optimizer.param_groups[0]['lr']\n",
    "                print(f\"Epoch {epoch:02d} | Tr Loss: {t_loss:.4f} | Tr Acc: {t_acc:.4f} | Val Acc: {v_acc:.4f} | Best Val: {best_acc:.4f}\")\n",
    "\n",
    "        best_vals.append(best_acc)\n",
    "        del train_loader, val_loader, model, optimizer, scheduler\n",
    "        gc.collect() # Ép Python dọn rác ngay lập tức\n",
    "        if torch.cuda.is_available():\n",
    "            torch.cuda.empty_cache() # Dọn rác VRAM của Card màn hình\n",
    "    \n",
    "    print(f\"\\n>>> TRUNG BÌNH K-FOLD ACCURACY (Tổ hợp {INPUT_CHANNELS}): {sum(best_vals) / len(best_vals):.4f}\")\n",
    "\n",
    "if __name__ == '__main__':\n",
    "    main()"
   ]
  }
 ],
 "metadata": {
  "kaggle": {
   "accelerator": "nvidiaTeslaT4",
   "dataSources": [
    {
     "databundleVersionId": 16542997,
     "datasetId": 9989031,
     "sourceId": 15609361,
     "sourceType": "datasetVersion"
    },
    {
     "sourceId": 310110736,
     "sourceType": "kernelVersion"
    }
   ],
   "dockerImageVersionId": 31328,
   "isGpuEnabled": true,
   "isInternetEnabled": true,
   "language": "python",
   "sourceType": "notebook"
  },
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.12"
  },
  "papermill": {
   "default_parameters": {},
   "duration": 4100.402414,
   "end_time": "2026-04-09T08:46:16.462655+00:00",
   "environment_variables": {},
   "exception": null,
   "input_path": "__notebook__.ipynb",
   "output_path": "__notebook__.ipynb",
   "parameters": {},
   "start_time": "2026-04-09T07:37:56.060241+00:00",
   "version": "2.7.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
