{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "41ccc684",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2026-04-10T04:38:59.428874Z",
     "iopub.status.busy": "2026-04-10T04:38:59.427981Z",
     "iopub.status.idle": "2026-04-10T04:39:09.741777Z",
     "shell.execute_reply": "2026-04-10T04:39:09.741040Z"
    },
    "papermill": {
     "duration": 10.319637,
     "end_time": "2026-04-10T04:39:09.743721+00:00",
     "exception": false,
     "start_time": "2026-04-10T04:38:59.424084+00:00",
     "status": "completed"
    },
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting torch_geometric\r\n",
      "  Downloading torch_geometric-2.7.0-py3-none-any.whl.metadata (63 kB)\r\n",
      "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m63.7/63.7 kB\u001b[0m \u001b[31m2.5 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\r\n",
      "\u001b[?25hRequirement already satisfied: aiohttp in /usr/local/lib/python3.12/dist-packages (from torch_geometric) (3.13.3)\r\n",
      "Requirement already satisfied: fsspec in /usr/local/lib/python3.12/dist-packages (from torch_geometric) (2026.2.0)\r\n",
      "Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch_geometric) (3.1.6)\r\n",
      "Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from torch_geometric) (2.0.2)\r\n",
      "Requirement already satisfied: psutil>=5.8.0 in /usr/local/lib/python3.12/dist-packages (from torch_geometric) (5.9.5)\r\n",
      "Requirement already satisfied: pyparsing in /usr/local/lib/python3.12/dist-packages (from torch_geometric) (3.3.2)\r\n",
      "Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from torch_geometric) (2.32.4)\r\n",
      "Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from torch_geometric) (4.67.3)\r\n",
      "Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from torch_geometric) (3.6.0)\r\n",
      "Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->torch_geometric) (2.6.1)\r\n",
      "Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->torch_geometric) (1.4.0)\r\n",
      "Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->torch_geometric) (25.4.0)\r\n",
      "Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp->torch_geometric) (1.8.0)\r\n",
      "Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp->torch_geometric) (6.7.1)\r\n",
      "Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->torch_geometric) (0.4.1)\r\n",
      "Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->torch_geometric) (1.22.0)\r\n",
      "Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch_geometric) (3.0.3)\r\n",
      "Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->torch_geometric) (3.4.4)\r\n",
      "Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->torch_geometric) (3.11)\r\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->torch_geometric) (2.5.0)\r\n",
      "Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->torch_geometric) (2026.1.4)\r\n",
      "Requirement already satisfied: typing-extensions>=4.2 in /usr/local/lib/python3.12/dist-packages (from aiosignal>=1.4.0->aiohttp->torch_geometric) (4.15.0)\r\n",
      "Downloading torch_geometric-2.7.0-py3-none-any.whl (1.3 MB)\r\n",
      "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m1.3/1.3 MB\u001b[0m \u001b[31m23.7 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\r\n",
      "\u001b[?25hInstalling collected packages: torch_geometric\r\n",
      "Successfully installed torch_geometric-2.7.0\r\n",
      "Looking in links: https://data.pyg.org/whl/torch-2.10.0+cu128.html\r\n",
      "Collecting torch-scatter\r\n",
      "  Downloading https://data.pyg.org/whl/torch-2.10.0%2Bcu128/torch_scatter-2.1.2%2Bpt210cu128-cp312-cp312-linux_x86_64.whl (10.9 MB)\r\n",
      "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m10.9/10.9 MB\u001b[0m \u001b[31m96.1 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\r\n",
      "\u001b[?25hInstalling collected packages: torch-scatter\r\n",
      "Successfully installed torch-scatter-2.1.2+pt210cu128\r\n"
     ]
    }
   ],
   "source": [
    "!pip install torch_geometric\n",
    "!pip install torch-scatter -f https://data.pyg.org/whl/torch-2.10.0+cu128.html"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "9dce82a7",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2026-04-10T04:39:09.749955Z",
     "iopub.status.busy": "2026-04-10T04:39:09.749538Z",
     "iopub.status.idle": "2026-04-10T04:39:09.754222Z",
     "shell.execute_reply": "2026-04-10T04:39:09.753376Z"
    },
    "papermill": {
     "duration": 0.009542,
     "end_time": "2026-04-10T04:39:09.755740+00:00",
     "exception": false,
     "start_time": "2026-04-10T04:39:09.746198+00:00",
     "status": "completed"
    },
    "tags": []
   },
   "outputs": [],
   "source": [
    "import csv\n",
    "import os\n",
    "\n",
    "file_path_check = \"/kaggle/working/confusion_result.csv\"\n",
    "if os.path.exists(file_path_check):\n",
    "    os.remove(file_path_check)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "8d66c2e3",
   "metadata": {
    "_cell_guid": "0ad39be2-d511-405b-876c-b8c85a5e2c27",
    "_uuid": "883f90f2-976d-453f-ab4a-90d1bfeb05b5",
    "collapsed": false,
    "execution": {
     "iopub.execute_input": "2026-04-10T04:39:09.761825Z",
     "iopub.status.busy": "2026-04-10T04:39:09.761234Z",
     "iopub.status.idle": "2026-04-10T06:18:19.175244Z",
     "shell.execute_reply": "2026-04-10T06:18:19.173618Z"
    },
    "jupyter": {
     "outputs_hidden": false
    },
    "papermill": {
     "duration": 5949.421609,
     "end_time": "2026-04-10T06:18:19.179442+00:00",
     "exception": false,
     "start_time": "2026-04-10T04:39:09.757833+00:00",
     "status": "completed"
    },
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Đang kiểm thử Tổ hợp: ['Fp1', 'Fp2', 'F7', 'F3', 'Fz', 'F4', 'F8', 'T3', 'C3', 'Cz', 'C4', 'T4', 'T5', 'P3', 'Pz', 'P4', 'T6', 'O1', 'O2'] (Indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18])\n",
      "Sử dụng thiết bị: cuda\n",
      ">>> Đang tải dữ liệu từ 88 subjects...\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/tmp/ipykernel_24/766312886.py:171: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.\n",
      "  df = pd.read_csv(tsv_path, sep=r'\\t')\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "===== Bắt đầu Training (Chế độ Voting: TẮT) =====\n",
      "\n",
      "===== Đang xử lý Fold 0 =====\n",
      ">>> Đang tải Ma trận Cấu trúc từ: /kaggle/input/notebooks/dtandat/mf-mgcn-processing/processed_data/structural_adjacency.csv\n",
      "    -> Tìm thấy 74 kết nối cấu trúc hợp lệ trên 19 kênh.\n",
      "Train Bệnh nhân: AD=23, NC=23\n",
      "+---------------------------------+---------------------------------+----------------+----------+\n",
      "| Layer                           | Input Shape                     | Output Shape   | #Param   |\n",
      "|---------------------------------+---------------------------------+----------------+----------|\n",
      "| UltimateResidualGAT             | [608, 608]                      | [32, 2]        | 36,643   |\n",
      "| ├─(proj)Linear                  | [608, 8]                        | [608, 32]      | 288      |\n",
      "| ├─(ln1)LayerNorm                | [608, 32]                       | [608, 32]      | 64       |\n",
      "| ├─(gat1)GATv2Conv               | [608, 32], [2, 2368], [2368, 1] | [608, 64]      | 4,416    |\n",
      "| ├─(gn1)GraphNorm                | [608, 64]                       | [608, 64]      | 192      |\n",
      "| ├─(gat2)GATv2Conv               | [608, 64], [2, 2368], [2368, 1] | [608, 64]      | 8,512    |\n",
      "| ├─(gn2)GraphNorm                | [608, 64]                       | [608, 64]      | 192      |\n",
      "| ├─(skip)Linear                  | [608, 32]                       | [608, 64]      | 2,112    |\n",
      "| ├─(spatial_attention)Sequential | [608, 128]                      | [608, 1]       | 4,161    |\n",
      "| │    └─(0)Linear                | [608, 128]                      | [608, 32]      | 4,128    |\n",
      "| │    └─(1)GELU                  | [608, 32]                       | [608, 32]      | --       |\n",
      "| │    └─(2)Linear                | [608, 32]                       | [608, 1]       | 33       |\n",
      "| ├─(classifier)Sequential        | [32, 256]                       | [32, 2]        | 16,706   |\n",
      "| │    └─(0)Linear                | [32, 256]                       | [32, 64]       | 16,448   |\n",
      "| │    └─(1)LayerNorm             | [32, 64]                        | [32, 64]       | 128      |\n",
      "| │    └─(2)Dropout               | [32, 64]                        | [32, 64]       | --       |\n",
      "| │    └─(3)GELU                  | [32, 64]                        | [32, 64]       | --       |\n",
      "| │    └─(4)Linear                | [32, 64]                        | [32, 2]        | 130      |\n",
      "+---------------------------------+---------------------------------+----------------+----------+\n",
      "Epoch 00 | Tr Loss: 0.4380 | Tr Acc: 0.8494 | Val Acc: 0.7113 | Best Val: 0.7113\n",
      "Epoch 10 | Tr Loss: 0.2616 | Tr Acc: 0.9694 | Val Acc: 0.7952 | Best Val: 0.8751\n",
      "Epoch 20 | Tr Loss: 0.2359 | Tr Acc: 0.9841 | Val Acc: 0.8522 | Best Val: 0.8751\n",
      "Epoch 30 | Tr Loss: 0.2234 | Tr Acc: 0.9921 | Val Acc: 0.8551 | Best Val: 0.8751\n",
      "Epoch 40 | Tr Loss: 0.2191 | Tr Acc: 0.9946 | Val Acc: 0.8425 | Best Val: 0.8751\n",
      "Epoch 50 | Tr Loss: 0.2170 | Tr Acc: 0.9957 | Val Acc: 0.8477 | Best Val: 0.8751\n",
      "Epoch 60 | Tr Loss: 0.2163 | Tr Acc: 0.9957 | Val Acc: 0.8508 | Best Val: 0.8751\n",
      "Epoch 70 | Tr Loss: 0.2167 | Tr Acc: 0.9963 | Val Acc: 0.8454 | Best Val: 0.8751\n",
      "Epoch 80 | Tr Loss: 0.2155 | Tr Acc: 0.9965 | Val Acc: 0.8462 | Best Val: 0.8751\n",
      "Epoch 90 | Tr Loss: 0.2149 | Tr Acc: 0.9972 | Val Acc: 0.8468 | Best Val: 0.8751\n",
      "Epoch 99 | Tr Loss: 0.2148 | Tr Acc: 0.9972 | Val Acc: 0.8448 | Best Val: 0.8751\n",
      "\n",
      "===== Đang xử lý Fold 1 =====\n",
      ">>> Đang tải Ma trận Cấu trúc từ: /kaggle/input/notebooks/dtandat/mf-mgcn-processing/processed_data/structural_adjacency.csv\n",
      "    -> Tìm thấy 74 kết nối cấu trúc hợp lệ trên 19 kênh.\n",
      "Train Bệnh nhân: AD=29, NC=23\n",
      "Epoch 00 | Tr Loss: 0.5035 | Tr Acc: 0.7896 | Val Acc: 0.8308 | Best Val: 0.8308\n",
      "Epoch 10 | Tr Loss: 0.2837 | Tr Acc: 0.9571 | Val Acc: 0.8163 | Best Val: 0.8855\n",
      "Epoch 20 | Tr Loss: 0.2479 | Tr Acc: 0.9792 | Val Acc: 0.7933 | Best Val: 0.8855\n",
      "Epoch 30 | Tr Loss: 0.2359 | Tr Acc: 0.9855 | Val Acc: 0.7602 | Best Val: 0.8855\n",
      "Epoch 40 | Tr Loss: 0.2276 | Tr Acc: 0.9915 | Val Acc: 0.7801 | Best Val: 0.8855\n",
      "Epoch 50 | Tr Loss: 0.2232 | Tr Acc: 0.9946 | Val Acc: 0.7555 | Best Val: 0.8855\n",
      "Epoch 60 | Tr Loss: 0.2209 | Tr Acc: 0.9955 | Val Acc: 0.7621 | Best Val: 0.8855\n",
      "Epoch 70 | Tr Loss: 0.2204 | Tr Acc: 0.9963 | Val Acc: 0.7639 | Best Val: 0.8855\n",
      "Epoch 80 | Tr Loss: 0.2205 | Tr Acc: 0.9964 | Val Acc: 0.7557 | Best Val: 0.8855\n",
      "Epoch 90 | Tr Loss: 0.2190 | Tr Acc: 0.9970 | Val Acc: 0.7542 | Best Val: 0.8855\n",
      "Epoch 99 | Tr Loss: 0.2202 | Tr Acc: 0.9966 | Val Acc: 0.7502 | Best Val: 0.8855\n",
      "\n",
      "===== Đang xử lý Fold 2 =====\n",
      ">>> Đang tải Ma trận Cấu trúc từ: /kaggle/input/notebooks/dtandat/mf-mgcn-processing/processed_data/structural_adjacency.csv\n",
      "    -> Tìm thấy 74 kết nối cấu trúc hợp lệ trên 19 kênh.\n",
      "Train Bệnh nhân: AD=29, NC=23\n",
      "Epoch 00 | Tr Loss: 0.5024 | Tr Acc: 0.7874 | Val Acc: 0.7727 | Best Val: 0.7727\n",
      "Epoch 10 | Tr Loss: 0.2798 | Tr Acc: 0.9574 | Val Acc: 0.8652 | Best Val: 0.8755\n",
      "Epoch 20 | Tr Loss: 0.2585 | Tr Acc: 0.9734 | Val Acc: 0.9048 | Best Val: 0.9048\n",
      "Epoch 30 | Tr Loss: 0.2514 | Tr Acc: 0.9770 | Val Acc: 0.8832 | Best Val: 0.9048\n",
      "Epoch 40 | Tr Loss: 0.2340 | Tr Acc: 0.9874 | Val Acc: 0.8242 | Best Val: 0.9048\n",
      "Epoch 50 | Tr Loss: 0.2257 | Tr Acc: 0.9924 | Val Acc: 0.8506 | Best Val: 0.9048\n",
      "Epoch 60 | Tr Loss: 0.2210 | Tr Acc: 0.9957 | Val Acc: 0.8623 | Best Val: 0.9048\n",
      "Epoch 70 | Tr Loss: 0.2187 | Tr Acc: 0.9971 | Val Acc: 0.8475 | Best Val: 0.9048\n",
      "Epoch 80 | Tr Loss: 0.2173 | Tr Acc: 0.9980 | Val Acc: 0.8380 | Best Val: 0.9048\n",
      "Epoch 90 | Tr Loss: 0.2185 | Tr Acc: 0.9973 | Val Acc: 0.8393 | Best Val: 0.9048\n",
      "Epoch 99 | Tr Loss: 0.2179 | Tr Acc: 0.9978 | Val Acc: 0.8427 | Best Val: 0.9048\n",
      "\n",
      "===== Đang xử lý Fold 3 =====\n",
      ">>> Đang tải Ma trận Cấu trúc từ: /kaggle/input/notebooks/dtandat/mf-mgcn-processing/processed_data/structural_adjacency.csv\n",
      "    -> Tìm thấy 74 kết nối cấu trúc hợp lệ trên 19 kênh.\n",
      "Train Bệnh nhân: AD=29, NC=24\n",
      "Epoch 00 | Tr Loss: 0.5121 | Tr Acc: 0.7804 | Val Acc: 0.7709 | Best Val: 0.7709\n",
      "Epoch 10 | Tr Loss: 0.2807 | Tr Acc: 0.9585 | Val Acc: 0.6509 | Best Val: 0.7709\n",
      "Epoch 20 | Tr Loss: 0.2510 | Tr Acc: 0.9763 | Val Acc: 0.6263 | Best Val: 0.7709\n",
      "Epoch 30 | Tr Loss: 0.2363 | Tr Acc: 0.9841 | Val Acc: 0.6323 | Best Val: 0.7709\n",
      "Epoch 40 | Tr Loss: 0.2278 | Tr Acc: 0.9898 | Val Acc: 0.6186 | Best Val: 0.7709\n",
      "Epoch 50 | Tr Loss: 0.2247 | Tr Acc: 0.9923 | Val Acc: 0.6386 | Best Val: 0.7709\n",
      "Epoch 60 | Tr Loss: 0.2230 | Tr Acc: 0.9931 | Val Acc: 0.6203 | Best Val: 0.7709\n",
      "Epoch 70 | Tr Loss: 0.2203 | Tr Acc: 0.9946 | Val Acc: 0.6177 | Best Val: 0.7709\n",
      "Epoch 80 | Tr Loss: 0.2212 | Tr Acc: 0.9946 | Val Acc: 0.6277 | Best Val: 0.7709\n",
      "Epoch 90 | Tr Loss: 0.2202 | Tr Acc: 0.9959 | Val Acc: 0.6168 | Best Val: 0.7709\n",
      "Epoch 99 | Tr Loss: 0.2200 | Tr Acc: 0.9956 | Val Acc: 0.6180 | Best Val: 0.7709\n",
      "\n",
      "===== Đang xử lý Fold 4 =====\n",
      ">>> Đang tải Ma trận Cấu trúc từ: /kaggle/input/notebooks/dtandat/mf-mgcn-processing/processed_data/structural_adjacency.csv\n",
      "    -> Tìm thấy 74 kết nối cấu trúc hợp lệ trên 19 kênh.\n",
      "Train Bệnh nhân: AD=29, NC=23\n",
      "Epoch 00 | Tr Loss: 0.5086 | Tr Acc: 0.7881 | Val Acc: 0.7954 | Best Val: 0.7954\n",
      "Epoch 10 | Tr Loss: 0.2863 | Tr Acc: 0.9570 | Val Acc: 0.8499 | Best Val: 0.9070\n",
      "Epoch 20 | Tr Loss: 0.2461 | Tr Acc: 0.9802 | Val Acc: 0.7928 | Best Val: 0.9070\n",
      "Epoch 30 | Tr Loss: 0.2333 | Tr Acc: 0.9880 | Val Acc: 0.8314 | Best Val: 0.9070\n",
      "Epoch 40 | Tr Loss: 0.2269 | Tr Acc: 0.9923 | Val Acc: 0.7798 | Best Val: 0.9070\n",
      "Epoch 50 | Tr Loss: 0.2232 | Tr Acc: 0.9946 | Val Acc: 0.7906 | Best Val: 0.9070\n",
      "Epoch 60 | Tr Loss: 0.2225 | Tr Acc: 0.9954 | Val Acc: 0.8002 | Best Val: 0.9070\n",
      "Epoch 70 | Tr Loss: 0.2225 | Tr Acc: 0.9951 | Val Acc: 0.7991 | Best Val: 0.9070\n",
      "Epoch 80 | Tr Loss: 0.2215 | Tr Acc: 0.9960 | Val Acc: 0.7909 | Best Val: 0.9070\n",
      "Epoch 90 | Tr Loss: 0.2217 | Tr Acc: 0.9960 | Val Acc: 0.7912 | Best Val: 0.9070\n",
      "Epoch 99 | Tr Loss: 0.2213 | Tr Acc: 0.9961 | Val Acc: 0.7888 | Best Val: 0.9070\n",
      "\n",
      "===== Đang xử lý Fold 5 =====\n",
      ">>> Đang tải Ma trận Cấu trúc từ: /kaggle/input/notebooks/dtandat/mf-mgcn-processing/processed_data/structural_adjacency.csv\n",
      "    -> Tìm thấy 74 kết nối cấu trúc hợp lệ trên 19 kênh.\n",
      "Train Bệnh nhân: AD=29, NC=23\n",
      "Epoch 00 | Tr Loss: 0.4620 | Tr Acc: 0.8360 | Val Acc: 0.5858 | Best Val: 0.5858\n",
      "Epoch 10 | Tr Loss: 0.2756 | Tr Acc: 0.9615 | Val Acc: 0.6759 | Best Val: 0.6815\n",
      "Epoch 20 | Tr Loss: 0.2418 | Tr Acc: 0.9827 | Val Acc: 0.6104 | Best Val: 0.6815\n",
      "Epoch 30 | Tr Loss: 0.2300 | Tr Acc: 0.9887 | Val Acc: 0.6051 | Best Val: 0.6815\n",
      "Epoch 40 | Tr Loss: 0.2234 | Tr Acc: 0.9935 | Val Acc: 0.6112 | Best Val: 0.6815\n",
      "Epoch 50 | Tr Loss: 0.2219 | Tr Acc: 0.9955 | Val Acc: 0.5924 | Best Val: 0.6815\n",
      "Epoch 60 | Tr Loss: 0.2212 | Tr Acc: 0.9956 | Val Acc: 0.5890 | Best Val: 0.6815\n",
      "Epoch 70 | Tr Loss: 0.2192 | Tr Acc: 0.9970 | Val Acc: 0.6022 | Best Val: 0.6815\n",
      "Epoch 80 | Tr Loss: 0.2183 | Tr Acc: 0.9972 | Val Acc: 0.5940 | Best Val: 0.6815\n",
      "Epoch 90 | Tr Loss: 0.2189 | Tr Acc: 0.9972 | Val Acc: 0.5921 | Best Val: 0.6815\n",
      "Epoch 99 | Tr Loss: 0.2190 | Tr Acc: 0.9972 | Val Acc: 0.5964 | Best Val: 0.6815\n",
      "\n",
      "===== Đang xử lý Fold 6 =====\n",
      ">>> Đang tải Ma trận Cấu trúc từ: /kaggle/input/notebooks/dtandat/mf-mgcn-processing/processed_data/structural_adjacency.csv\n",
      "    -> Tìm thấy 74 kết nối cấu trúc hợp lệ trên 19 kênh.\n",
      "Train Bệnh nhân: AD=29, NC=23\n",
      "Epoch 00 | Tr Loss: 0.4885 | Tr Acc: 0.8084 | Val Acc: 0.6677 | Best Val: 0.6677\n",
      "Epoch 10 | Tr Loss: 0.2894 | Tr Acc: 0.9533 | Val Acc: 0.7367 | Best Val: 0.7367\n",
      "Epoch 20 | Tr Loss: 0.2654 | Tr Acc: 0.9683 | Val Acc: 0.7777 | Best Val: 0.7777\n",
      "Epoch 30 | Tr Loss: 0.2584 | Tr Acc: 0.9738 | Val Acc: 0.6741 | Best Val: 0.7777\n",
      "Epoch 40 | Tr Loss: 0.2405 | Tr Acc: 0.9833 | Val Acc: 0.6667 | Best Val: 0.7777\n",
      "Epoch 50 | Tr Loss: 0.2271 | Tr Acc: 0.9919 | Val Acc: 0.6994 | Best Val: 0.7777\n",
      "Epoch 60 | Tr Loss: 0.2219 | Tr Acc: 0.9947 | Val Acc: 0.7018 | Best Val: 0.7777\n",
      "Epoch 70 | Tr Loss: 0.2201 | Tr Acc: 0.9963 | Val Acc: 0.7211 | Best Val: 0.7777\n",
      "Epoch 80 | Tr Loss: 0.2191 | Tr Acc: 0.9968 | Val Acc: 0.7068 | Best Val: 0.7777\n",
      "Epoch 90 | Tr Loss: 0.2182 | Tr Acc: 0.9972 | Val Acc: 0.7061 | Best Val: 0.7777\n",
      "Epoch 99 | Tr Loss: 0.2189 | Tr Acc: 0.9964 | Val Acc: 0.7113 | Best Val: 0.7777\n",
      "\n",
      ">>> TRUNG BÌNH K-FOLD ACCURACY (Tổ hợp ['Fp1', 'Fp2', 'F7', 'F3', 'Fz', 'F4', 'F8', 'T3', 'C3', 'Cz', 'C4', 'T4', 'T5', 'P3', 'Pz', 'P4', 'T6', 'O1', 'O2']): 0.8289\n"
     ]
    }
   ],
   "source": [
    "import torch\n",
    "import torch.nn as nn\n",
    "import torch.nn.functional as F\n",
    "import os\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import random\n",
    "from sklearn.preprocessing import StandardScaler\n",
    "from sklearn.metrics import f1_score, accuracy_score, recall_score, confusion_matrix\n",
    "import sys\n",
    "from collections import defaultdict\n",
    "import csv\n",
    "import gc\n",
    "from torch_geometric.nn import GATv2Conv, BatchNorm\n",
    "from torch_geometric.nn import global_mean_pool, global_max_pool\n",
    "from torch_geometric.nn.norm import GraphNorm\n",
    "from torch_geometric.data import Data\n",
    "from torch_geometric.loader import DataLoader\n",
    "from torch_geometric.nn import summary\n",
    "from torch_geometric.utils import softmax, dropout_edge\n",
    "\n",
    "# =====================================================================\n",
    "# CẤU HÌNH HỆ THỐNG\n",
    "# =====================================================================\n",
    "USE_MAJORITY_VOTING = False  # Đổi thành True để dùng Voting cấp độ bệnh nhân\n",
    "NUM_FEATURES = 8             # Số đặc trưng mỗi nút (5 PSD + 3 Hjorth)\n",
    "\n",
    "ALL_19_CHANNELS = [\n",
    "    'Fp1', 'Fp2', 'F7', 'F3', 'Fz', 'F4', 'F8', \n",
    "    'T3', 'C3', 'Cz', 'C4', 'T4', 'T5', 'P3', \n",
    "    'Pz', 'P4', 'T6', 'O1', 'O2'\n",
    "]\n",
    "\n",
    "def seed_everything(seed=42):\n",
    "    random.seed(seed)\n",
    "    np.random.seed(seed)\n",
    "    torch.manual_seed(seed)\n",
    "\n",
    "# =====================================================================\n",
    "# KIẾN TRÚC AI SOTA: DYNAMIC GRAPH TRANSFORMER (DÀNH CHO 3 KÊNH)\n",
    "# =====================================================================\n",
    "from torch_geometric.utils import softmax\n",
    "from torch_geometric.nn import global_add_pool\n",
    "\n",
    "from torch_geometric.utils import softmax, dropout_adj\n",
    "from torch_geometric.nn import global_mean_pool, global_max_pool\n",
    "import torch.nn as nn\n",
    "import torch.nn.functional as F\n",
    "\n",
    "class UltimateResidualGAT(nn.Module):\n",
    "    def __init__(self, num_nodes=19, in_features=NUM_FEATURES, num_classes=2):\n",
    "        super(UltimateResidualGAT, self).__init__()\n",
    "        \n",
    "        # 1. Phóng chiếu Đặc trưng (LayerNorm tốt hơn BatchNorm cho EEG)\n",
    "        self.proj = nn.Linear(in_features, 32)\n",
    "        self.ln1 = nn.LayerNorm(32) \n",
    "        \n",
    "        # 2. Block GAT 1: Học cục bộ\n",
    "        self.gat1 = GATv2Conv(32, 16, heads=4, concat=True, edge_dim=1, dropout=0.5)\n",
    "        self.gn1 = GraphNorm(64) # 16 * 4\n",
    "        \n",
    "        # 3. Block GAT 2: Học toàn cục\n",
    "        self.gat2 = GATv2Conv(64, 16, heads=4, concat=True, edge_dim=1, dropout=0.5)\n",
    "        self.gn2 = GraphNorm(64)\n",
    "        \n",
    "        # 4. KẾT NỐI TẮT (Residual Skip Connection) - Vũ khí bí mật chống Over-smoothing\n",
    "        self.skip = nn.Linear(32, 64)\n",
    "        \n",
    "        # 5. Khối Attention Không gian (Spatial Attention)\n",
    "        self.spatial_attention = nn.Sequential(\n",
    "            nn.Linear(128, 32), # Sẽ nhận feature sau khi nối (64 + 64)\n",
    "            nn.GELU(),\n",
    "            nn.Linear(32, 1)\n",
    "        )\n",
    "        \n",
    "        # 6. MLP Phân loại Chống Overfit hạng nặng\n",
    "        self.classifier = nn.Sequential(\n",
    "            nn.Linear(256, 64), # Nhận 128 Mean + 128 Max\n",
    "            nn.LayerNorm(64),\n",
    "            nn.Dropout(p=0.6), # Ép rớt 60% nơ-ron để không học vẹt\n",
    "            nn.GELU(),\n",
    "            nn.Linear(64, num_classes)\n",
    "        )\n",
    "\n",
    "    def forward(self, data):\n",
    "        x, edge_index, edge_attr, batch = data.x, data.edge_index, data.edge_attr, data.batch\n",
    "        \n",
    "        # --- KỸ THUẬT DROP-EDGE (Chỉ bật khi Train) ---\n",
    "        # Ngẫu nhiên vô hiệu hóa 20% kết nối cấu trúc. Ép mô hình nhìn vào bức tranh tổng thể!\n",
    "# --- KỸ THUẬT DROP-EDGE (Chỉ bật khi Train) ---\n",
    "        # Ngẫu nhiên vô hiệu hóa 20% kết nối cấu trúc. Ép mô hình nhìn vào bức tranh tổng thể!\n",
    "        if self.training:\n",
    "            # dropout_edge sẽ trả về ma trận cạnh mới và một edge_mask (boolean)\n",
    "            edge_index, edge_mask = dropout_edge(edge_index, p=0.2, force_undirected=True)\n",
    "            \n",
    "            # Sử dụng mask để lọc edge_attr, đảm bảo số lượng cạnh và trọng số khớp nhau 100%\n",
    "            edge_attr = edge_attr[edge_mask]\n",
    "        # Tiền xử lý\n",
    "        x_proj = self.proj(x)\n",
    "        x_proj = self.ln1(x_proj)\n",
    "        x_proj = F.gelu(x_proj)\n",
    "        \n",
    "        # GAT Lớp 1\n",
    "        x1 = self.gat1(x_proj, edge_index, edge_attr)\n",
    "        x1 = self.gn1(x1)\n",
    "        x1 = F.gelu(x1)\n",
    "        \n",
    "        # GAT Lớp 2\n",
    "        x2 = self.gat2(x1, edge_index, edge_attr)\n",
    "        x2 = self.gn2(x2)\n",
    "        x2 = F.gelu(x2)\n",
    "        \n",
    "        # --- FEATURE FUSION & RESIDUAL ---\n",
    "        # Nối đặc trưng của Block 1 và Block 2 + Đường truyền tắt từ tín hiệu gốc\n",
    "        x_res = self.skip(x_proj)\n",
    "        x_fused = torch.cat([x1, x2 + x_res], dim=1) # [Batch_size * 19, 128]\n",
    "        \n",
    "        # --- SPATIAL ATTENTION POOLING ---\n",
    "        attn_scores = self.spatial_attention(x_fused)\n",
    "        attn_scores = softmax(attn_scores, batch)\n",
    "        x_weighted = x_fused * attn_scores\n",
    "        \n",
    "        # --- KỸ THUẬT DUAL READOUT ---\n",
    "        x_mean = global_mean_pool(x_weighted, batch) # Bắt tín hiệu nền có trọng số\n",
    "        x_max = global_max_pool(x_fused, batch)      # Bắt các gai bất thường (Không nhân trọng số để tránh mất gai)\n",
    "        \n",
    "        x_out = torch.cat([x_mean, x_max], dim=1) # [Batch_size, 256]\n",
    "        \n",
    "        # Phân loại\n",
    "        logits = self.classifier(x_out)\n",
    "        return logits\n",
    "\n",
    "# =====================================================================\n",
    "# HÀM XỬ LÝ DỮ LIỆU & BATCHING\n",
    "# =====================================================================\n",
    "def load_structural_prior(csv_path):\n",
    "    print(f\">>> Đang tải Ma trận Cấu trúc từ: {csv_path}\")\n",
    "    \n",
    "    # Đọc file CSV. Tùy thuộc vào file của bạn có header hay không, bạn có thể chỉnh sửa `header`\n",
    "    try:\n",
    "        # Nếu file có tên cột/hàng (VD: Fp1, Fp2...)\n",
    "        df = pd.read_csv(csv_path, index_col=0)\n",
    "        adj_matrix = df.values\n",
    "    except:\n",
    "        # Nếu file chỉ là ma trận số thuần túy\n",
    "        df = pd.read_csv(csv_path, header=None)\n",
    "        adj_matrix = df.values\n",
    "\n",
    "    # Ép về float32 để tương thích với PyTorch\n",
    "    adj_matrix = np.nan_to_num(adj_matrix, nan=0.0).astype(np.float32)\n",
    "    \n",
    "    # Tìm tọa độ của các cạnh có kết nối (giá trị > 0)\n",
    "    sources, targets = np.where(adj_matrix > 0)\n",
    "    \n",
    "    # Tạo edge_index cho PyTorch Geometric\n",
    "    edge_index = torch.tensor(np.vstack((sources, targets)), dtype=torch.long)\n",
    "    \n",
    "    # Lấy trọng số khởi tạo của cấu trúc não (nếu file CSV chỉ chứa 0 và 1 thì đây sẽ là mảng toàn 1)\n",
    "    edge_attr = torch.tensor(adj_matrix[sources, targets], dtype=torch.float32).unsqueeze(1)\n",
    "    \n",
    "    print(f\"    -> Tìm thấy {edge_index.shape[1]} kết nối cấu trúc hợp lệ trên 19 kênh.\")\n",
    "    return edge_index, edge_attr\n",
    "    \n",
    "def load_raw_data_dict():\n",
    "    BASE_DIR_01 = '/kaggle/input/notebooks/dtandat/mf-mgcn-processing'\n",
    "    PROCESSED_DIR = os.path.join(BASE_DIR_01, \"processed_data\")\n",
    "    BASE_DIR_02 = '/kaggle/input/datasets/dtandat/mf-mgcn-datasets/ds004504'\n",
    "    tsv_path = os.path.join(BASE_DIR_02, \"participants.tsv\")\n",
    "\n",
    "    try:\n",
    "        df = pd.read_csv(tsv_path, sep=r'\\t')\n",
    "    except:\n",
    "        df = pd.read_csv(tsv_path, sep=r'\\s+')\n",
    "    \n",
    "    sub_label_map = {}\n",
    "    for _, row in df.iterrows():\n",
    "        sub = row['participant_id']\n",
    "        grp = str(row['Group']).strip()\n",
    "        if grp == 'A': sub_label_map[sub] = 'AD'\n",
    "        elif grp == 'C': sub_label_map[sub] = 'NC'\n",
    "    \n",
    "    raw_data_dict = {'AD':[], 'NC':[]}\n",
    "    files = sorted([f for f in os.listdir(PROCESSED_DIR) if f.endswith('_features.npy')])\n",
    "    \n",
    "    print(f\">>> Đang tải dữ liệu từ {len(files)} subjects...\")\n",
    "    for f in files:\n",
    "        sub_id = f.split('_')[0]\n",
    "        if sub_id not in sub_label_map: continue\n",
    "        \n",
    "        features_raw = np.load(os.path.join(PROCESSED_DIR, f))\n",
    "        features_raw = np.nan_to_num(features_raw, nan=0.0)\n",
    "        raw_data_dict[sub_label_map[sub_id]].append({\n",
    "            'features': features_raw,\n",
    "            'id': sub_id\n",
    "        })\n",
    "    \n",
    "    return raw_data_dict\n",
    "\n",
    "def create_dataloaders(raw_data_dict, combo_indices, train_indices, val_indices, batch_size=32):\n",
    "    scaler = StandardScaler()\n",
    "    ad_list, nc_list = raw_data_dict['AD'], raw_data_dict['NC']\n",
    "    ad_ids = {item['id'] for item in ad_list}\n",
    "    \n",
    "    def get_subs(indices, source_list):\n",
    "        return [source_list[i] for i in indices if i < len(source_list)]\n",
    "    \n",
    "    train_subs = get_subs(train_indices['AD'], ad_list) + get_subs(train_indices['NC'], nc_list)\n",
    "    val_subs = get_subs(val_indices['AD'], ad_list) + get_subs(val_indices['NC'], nc_list)\n",
    "\n",
    "    if not train_subs: return None, None, 0, 0\n",
    "\n",
    "    # [SỬA LỖI TẠI ĐÂY] Gom toàn bộ dữ liệu Train và duỗi thành 2D\n",
    "    all_train_data = np.vstack([sub['features'] for sub in train_subs])\n",
    "    # all_train_data đang có shape: (Tổng số đoạn, 19, 8) -> Ép về: (Tổng số đoạn * 19, 8)\n",
    "    all_train_data_2d = all_train_data.reshape(-1, NUM_FEATURES)\n",
    "    scaler.fit(all_train_data_2d)\n",
    "\n",
    "    # Khởi tạo đồ thị 3 Nút (9 Cạnh Fully Connected) cho GATv2\n",
    "    # [ĐÃ SỬA] Khởi tạo đồ thị Fully Connected cho 19 Nút\n",
    "    num_nodes = len(combo_indices) # 19\n",
    "    edges = [[i, j] for i in range(num_nodes) for j in range(num_nodes) if i != j] # Bỏ self-loop ban đầu, PyG sẽ tự thêm\n",
    "    edge_index = torch.tensor(edges, dtype=torch.long).t().contiguous()\n",
    "    \n",
    "    # Khởi tạo edge_attr ban đầu bằng 1.0 (Mô hình sẽ tự học điều chỉnh sau)\n",
    "    edge_attr = torch.ones((edge_index.shape[1], 1), dtype=torch.float32)\n",
    "\n",
    "    CSV_PATH = '/kaggle/input/notebooks/dtandat/mf-mgcn-processing/processed_data/structural_adjacency.csv'\n",
    "    global_edge_index, global_edge_attr = load_structural_prior(CSV_PATH)\n",
    "    num_edges = global_edge_index.shape[1]\n",
    "    \n",
    "    def convert_to_pyg(sub_list):\n",
    "        data_list = []\n",
    "        cnt_0, cnt_1 = 0, 0\n",
    "        \n",
    "        for sub in sub_list:\n",
    "            sub_feats = sub['features']\n",
    "            n_segs = sub_feats.shape[0]\n",
    "            \n",
    "            # [SỬA LỖI TẠI ĐÂY] Duỗi thành 2D để transform, sau đó gấp lại thành 3D\n",
    "            sub_feats_2d = sub_feats.reshape(-1, NUM_FEATURES)\n",
    "            feats_scaled_2d = np.nan_to_num(scaler.transform(sub_feats_2d))\n",
    "            \n",
    "            # Khôi phục shape gốc (Epochs, 19 Kênh, 8 Đặc trưng)\n",
    "            features_3d = feats_scaled_2d.reshape(n_segs, 19, NUM_FEATURES)\n",
    "            \n",
    "            # [SLICE] Cắt lấy đúng 3 kênh đang xét (Sức mạnh của vét cạn nằm ở đây)\n",
    "            features_3d_subset = features_3d[:, combo_indices, :]\n",
    "            \n",
    "            y_label = 0 if sub['id'] in ad_ids else 1\n",
    "            if y_label == 0: cnt_0 += 1\n",
    "            else: cnt_1 += 1\n",
    "\n",
    "            for i in range(n_segs):\n",
    "                x = torch.tensor(features_3d_subset[i], dtype=torch.float32)\n",
    "                y = torch.tensor([y_label], dtype=torch.long)\n",
    "                \n",
    "                # Gán edge_index và edge_attr từ file CSV thay vì đồ thị tĩnh\n",
    "                data = Data(x=x, y=y, edge_index=global_edge_index, edge_attr=global_edge_attr, sub_id=sub['id'], segment=i)\n",
    "                data_list.append(data)\n",
    "                \n",
    "        return data_list, cnt_0, cnt_1, num_edges\n",
    "    \n",
    "    train_data, t_cnt_0, t_cnt_1, num_edges = convert_to_pyg(train_subs)\n",
    "    val_data, _, _, _ = convert_to_pyg(val_subs)\n",
    "    \n",
    "    print(f\"Train Bệnh nhân: AD={t_cnt_0}, NC={t_cnt_1}\")\n",
    "\n",
    "    train_loader = DataLoader(train_data, batch_size=batch_size, shuffle=True)\n",
    "    val_loader = DataLoader(val_data, batch_size=batch_size, shuffle=False)\n",
    "    \n",
    "    return train_loader, val_loader, t_cnt_0, t_cnt_1, num_edges\n",
    "\n",
    "# =====================================================================\n",
    "# VÒNG LẶP HUẤN LUYỆN & ĐÁNH GIÁ\n",
    "# =====================================================================\n",
    "def train_epoch(model, loader, criterion, optimizer, device):\n",
    "    model.train()\n",
    "    total_loss, total_correct, total_samples = 0, 0, 0\n",
    "    \n",
    "    for data in loader:\n",
    "        data = data.to(device)\n",
    "        optimizer.zero_grad()\n",
    "        out = model(data)\n",
    "        loss = criterion(out, data.y)\n",
    "        loss.backward()\n",
    "        optimizer.step()\n",
    "\n",
    "        total_loss += loss.item() * data.num_graphs\n",
    "        total_correct += (out.argmax(dim=1) == data.y).sum().item()\n",
    "        total_samples += data.num_graphs\n",
    "\n",
    "    return total_loss / total_samples, total_correct / total_samples\n",
    "\n",
    "def evaluate(model, loader, criterion, device):\n",
    "    model.eval()\n",
    "    \n",
    "    if USE_MAJORITY_VOTING:\n",
    "        # CHẤM ĐIỂM THEO MAJORITY VOTING (SUBJECT-LEVEL)\n",
    "        patient_preds = defaultdict(list)\n",
    "        patient_trues = defaultdict(int)\n",
    "        total_samples, total_loss = 0, 0\n",
    "\n",
    "        with torch.no_grad():\n",
    "            for data in loader:\n",
    "                data = data.to(device)\n",
    "                out = model(data)\n",
    "                loss = criterion(out, data.y)\n",
    "                preds = out.argmax(dim=1).cpu().tolist()\n",
    "                trues = data.y.cpu().tolist()\n",
    "                sub_ids = data.sub_id\n",
    "                \n",
    "                total_loss += loss.item() * data.num_graphs\n",
    "                total_samples += data.num_graphs\n",
    "                \n",
    "                for i in range(len(sub_ids)):\n",
    "                    sub_id = sub_ids[i]\n",
    "                    patient_preds[sub_id].append(preds[i])\n",
    "                    patient_trues[sub_id] = trues[i]\n",
    "        \n",
    "        final_preds, final_trues = [], []\n",
    "        for sub_id, preds_list in patient_preds.items():\n",
    "            count_0 = preds_list.count(0)\n",
    "            count_1 = preds_list.count(1)\n",
    "            final_vote = 1 if count_1 > count_0 else 0\n",
    "            final_preds.append(final_vote)\n",
    "            final_trues.append(patient_trues[sub_id])\n",
    "\n",
    "        loss = total_loss / total_samples\n",
    "        acc = accuracy_score(final_trues, final_preds)\n",
    "        f1 = f1_score(final_trues, final_preds, average='macro', zero_division=0)\n",
    "        recall = recall_score(final_trues, final_preds, average='macro', zero_division=0)\n",
    "        \n",
    "    else:\n",
    "        # CHẤM ĐIỂM THEO ĐOẠN (SEGMENT-LEVEL)\n",
    "        total_correct, total_samples, total_loss = 0, 0, 0\n",
    "        all_targets, all_preds = [], []\n",
    "        \n",
    "        with torch.no_grad():\n",
    "            for data in loader:\n",
    "                data = data.to(device)\n",
    "                out = model(data)\n",
    "                loss = criterion(out, data.y)\n",
    "                pred = out.argmax(dim=1)\n",
    "\n",
    "                is_file_exists = os.path.isfile(file_path_check)\n",
    "\n",
    "                with open(file_path_check, mode='a', newline='') as file:\n",
    "                    writer = csv.writer(file)\n",
    "\n",
    "                    if not is_file_exists:\n",
    "                        writer.writerow(['ID', 'SEGMENT'])\n",
    "\n",
    "                    for i in range(data.num_graphs):\n",
    "                        if pred[i] != data[i].y:\n",
    "                            writer.writerow([data[i].sub_id, data[i].segment.item()])\n",
    "                \n",
    "                total_loss += loss.item() * data.num_graphs\n",
    "                total_correct += (pred == data.y).sum().item()\n",
    "                total_samples += data.num_graphs\n",
    "                \n",
    "                all_targets.extend(data.y.cpu().tolist())\n",
    "                all_preds.extend(pred.cpu().tolist())\n",
    "            \n",
    "        acc = total_correct / total_samples\n",
    "        loss = total_loss / total_samples\n",
    "        f1 = f1_score(all_targets, all_preds, average='macro', zero_division=0)\n",
    "        recall = recall_score(all_targets, all_preds, average='macro', zero_division=0)\n",
    "\n",
    "    return acc, f1, recall, loss\n",
    "\n",
    "def main():\n",
    "    # Nhận 3 kênh từ Terminal (VD: python train.py Fp1 F8 Pz)\n",
    "    # INPUT_CHANNELS = sys.argv[1:]\n",
    "    INPUT_CHANNELS = [\n",
    "    'Fp1', 'Fp2', 'F7', 'F3', 'Fz', 'F4', 'F8', \n",
    "    'T3', 'C3', 'Cz', 'C4', 'T4', 'T5', 'P3', \n",
    "    'Pz', 'P4', 'T6', 'O1', 'O2'\n",
    "    ]\n",
    "    if len(INPUT_CHANNELS) != 19:\n",
    "        print(\"Vui lòng truyền đúng 3 kênh. VD: python train.py Fp1 F8 Pz\")\n",
    "        sys.exit(1)\n",
    "        \n",
    "    # Ánh xạ tên kênh thành Index (0-18)\n",
    "    combo_indices = [ALL_19_CHANNELS.index(ch) for ch in INPUT_CHANNELS]\n",
    "    print(f\"Đang kiểm thử Tổ hợp: {INPUT_CHANNELS} (Indices: {combo_indices})\")\n",
    "\n",
    "    seed_everything(42)\n",
    "    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')\n",
    "    print(f\"Sử dụng thiết bị: {device}\")\n",
    "\n",
    "    raw_data_dict = load_raw_data_dict()\n",
    "\n",
    "    folds_indices = [        \n",
    "        ([21, 2, 24, 11, 19, 30, 14, 35, 27, 0, 3, 10, 6, 12, 31, 4, 32, 25, 33, 13, 7, 28, 26], [15, 22, 20, 34, 16, 29], [17, 25, 19, 0, 3, 16, 10, 6, 12, 2, 4, 22, 13, 7, 9, 18, 28, 8, 1, 5, 23, 14, 26], [11, 21, 27, 15, 20, 24]),\n",
    "        ([18, 35, 32, 11, 2, 7, 5, 4, 22, 25, 13, 14, 6, 21, 26, 29, 9, 19, 1, 23, 12, 17, 20, 24, 15, 10, 31, 30, 0], [34, 16, 3, 28, 27, 33, 8], [8, 13, 5, 4, 21, 23, 16, 28, 14, 6, 22, 18, 9, 19, 1, 12, 17, 20, 24, 15, 10, 0, 7], [11, 3, 27, 26, 25, 2]),\n",
    "        ([0, 1, 3, 4, 5, 7, 8, 9, 11, 12, 13, 14, 16, 17, 18, 19, 20, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 33, 35], [2, 6, 10, 15, 21, 32, 34], [0, 2, 3, 4, 5, 6, 7, 8, 9, 11, 12, 13, 14, 17, 18, 19, 21, 22, 23, 24, 25, 26, 28], [1, 10, 15, 16, 20, 27]),\n",
    "        ([1, 2, 3, 4, 5, 6, 8, 9, 10, 11, 12, 14, 15, 18, 19, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 34, 35], [0, 7, 13, 16, 17, 20, 33], [0, 1, 3, 4, 5, 6, 7, 8, 10, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 26, 27, 28], [2, 9, 11, 24, 25]),\n",
    "        ([1, 2, 5, 7, 8, 9, 10, 11, 12, 13, 14, 15, 17, 18, 19, 20, 21, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 34, 35], [0, 3, 4, 6, 16, 22, 33], [0, 1, 3, 4, 5, 6, 8, 10, 11, 12, 14, 15, 16, 17, 18, 19, 21, 22, 23, 24, 25, 26, 28], [2, 7, 9, 13, 20, 27]),\n",
    "        ([15, 22, 17, 20, 34, 16, 29, 35, 27, 0, 3, 10, 6, 12, 31, 4, 32, 25, 33, 13, 7, 28, 26, 9, 18, 8, 23, 1, 5], [21, 2, 24, 11, 19, 30, 14], [11, 21, 27, 15, 20, 24, 10, 6, 12, 2, 4, 22, 13, 7, 9, 18, 28, 8, 1, 5, 23, 14, 26], [17, 25, 19, 0, 3, 16]),\n",
    "        ([15, 22, 17, 20, 34, 16, 29, 21, 2, 24, 11, 19, 30, 14, 31, 4, 32, 25, 33, 13, 7, 28, 26, 9, 18, 8, 23, 1, 5], [35, 27, 0, 3, 10, 6, 12], [11, 21, 27, 15, 20, 24, 17, 25, 19, 0, 3, 16, 13, 7, 9, 18, 28, 8, 1, 5, 23, 14, 26], [10, 6, 12, 2, 4, 22])\n",
    "    ]\n",
    "\n",
    "    print(f\"===== Bắt đầu Training (Chế độ Voting: {'BẬT' if USE_MAJORITY_VOTING else 'TẮT'}) =====\")\n",
    "    best_vals = []\n",
    "    \n",
    "    for fold_idx, (tr_ad, val_ad, tr_nc, val_nc) in enumerate(folds_indices):\n",
    "        print(f\"\\n===== Đang xử lý Fold {fold_idx} =====\")\n",
    "        \n",
    "        train_loader, val_loader, t_cnt_0, t_cnt_1, num_edges = create_dataloaders(\n",
    "            raw_data_dict, combo_indices,\n",
    "            {'AD': tr_ad, 'NC': tr_nc},\n",
    "            {'AD': val_ad, 'NC': val_nc}\n",
    "        )\n",
    "\n",
    "        # Khởi tạo mô hình Masked GAT với đúng số lượng cạnh vật lý\n",
    "        model = UltimateResidualGAT().to(device)\n",
    "        \n",
    "        # In tóm tắt mô hình ở Fold 0\n",
    "        if fold_idx == 0:\n",
    "            dummy_data = next(iter(train_loader)).to(device)\n",
    "            try: print(summary(model, dummy_data))\n",
    "            except Exception as e: pass\n",
    "\n",
    "        optimizer = torch.optim.Adam(model.parameters(), lr=0.001, weight_decay=5e-3)\n",
    "        scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode='max', factor=0.5, patience=10)\n",
    "        \n",
    "        # Tự động tính trọng số cân bằng lớp (Class Imbalance Weights)\n",
    "        weights = torch.tensor([1.0 / t_cnt_0, 1.0 / t_cnt_1], dtype=torch.float32).to(device)\n",
    "        weights = weights / weights.sum() \n",
    "        criterion = nn.CrossEntropyLoss(weight=weights, label_smoothing=0.1)\n",
    "\n",
    "        best_acc = 0.0\n",
    "        for epoch in range(100):\n",
    "            t_loss, t_acc = train_epoch(model, train_loader, criterion, optimizer, device)\n",
    "            v_acc, v_f1, v_recall, v_loss = evaluate(model, val_loader, criterion, device)\n",
    "            scheduler.step(v_acc)\n",
    "            \n",
    "            if v_acc > best_acc: best_acc = v_acc\n",
    "            \n",
    "            if epoch % 10 == 0 or epoch == 99:\n",
    "                lr = optimizer.param_groups[0]['lr']\n",
    "                print(f\"Epoch {epoch:02d} | Tr Loss: {t_loss:.4f} | Tr Acc: {t_acc:.4f} | Val Acc: {v_acc:.4f} | Best Val: {best_acc:.4f}\")\n",
    "\n",
    "        best_vals.append(best_acc)\n",
    "        del train_loader, val_loader, model, optimizer, scheduler\n",
    "        gc.collect() # Ép Python dọn rác ngay lập tức\n",
    "        if torch.cuda.is_available():\n",
    "            torch.cuda.empty_cache() # Dọn rác VRAM của Card màn hình\n",
    "    \n",
    "    print(f\"\\n>>> TRUNG BÌNH K-FOLD ACCURACY (Tổ hợp {INPUT_CHANNELS}): {sum(best_vals) / len(best_vals):.4f}\")\n",
    "\n",
    "if __name__ == '__main__':\n",
    "    main()"
   ]
  }
 ],
 "metadata": {
  "kaggle": {
   "accelerator": "nvidiaTeslaT4",
   "dataSources": [
    {
     "databundleVersionId": 16542997,
     "datasetId": 9989031,
     "sourceId": 15609361,
     "sourceType": "datasetVersion"
    },
    {
     "sourceId": 310110736,
     "sourceType": "kernelVersion"
    }
   ],
   "dockerImageVersionId": 31328,
   "isGpuEnabled": true,
   "isInternetEnabled": true,
   "language": "python",
   "sourceType": "notebook"
  },
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.12"
  },
  "papermill": {
   "default_parameters": {},
   "duration": 5965.306696,
   "end_time": "2026-04-10T06:18:22.069347+00:00",
   "environment_variables": {},
   "exception": null,
   "input_path": "__notebook__.ipynb",
   "output_path": "__notebook__.ipynb",
   "parameters": {},
   "start_time": "2026-04-10T04:38:56.762651+00:00",
   "version": "2.7.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
